sync/consul_test.go
sync/presets.go
sync/subtree.go
sync/watch.go

Introduces a Barrier synchronisation primitive, useful for distributed test scenarios where many nodes signal their entry into a condition, and peers need to wait until N nodes have entered that condition.

sync: add Barrier feature.

---

cmd/build.go
cmd/run.go
manifests/dht.toml
pkg/runner/local_docker.go
pkg/util/options.go
plans/dht/lookup_peers.go

Now we can provide parameters to test cases. There are three types of parameters/options passable via LCI:
* builder configuration overrides, e.g. bypass the cache.
* runner configuration overrides, e.g. log level.
* test parameters: settings that are specific to the test behaviour, e.g. bucket size, timeout values, etc.

propagate test parameters from CLI to runenv.

---

.pre-commit-config.yaml
Makefile
README.md

* uses the fantastic pre-commit project to manage hooks: github.com/pre-commit/pre-commit
* introduces a Makefile to facilitate installation and initialisation of pre-commit for new devs.
* adds the following go hooks: golangci-lint.
* adds a few general sanity check hooks.
* enhances the README.

Add precommit hooks

---

sdk/sync/common.go

Prefer user-specified redis hostname.

fix(redis): don't override user-specified redis host

---

go.mod
go.sum
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go

1. Use separate control/data networks everywhere.
2. Create a new data network for every run.
I've tested the local docker runner changes but am unsure how to test it on AWS.

feat(runner): separate control and per-run data networks

---

pkg/runner/cluster_swarm.go

* Fix the `rm_service` flag. mergo and boolean zero values don't get along. We now default to all boolean flags having semantics such that the default value is false.
* Remove the IPv6 configuration that was breaking in AWS, and we don't need it now.

Fix several bugs in the `cluster:swarm` runner

---

README.md

@nonsense, just came out of a chat with @jimpick and we found that now that you have been onboarded to the project and are tacking more and more responsibility in how TestGround provides a complete Service to the team, it makes sense (as it was planned) for you to also own the work that @jimpick has valiantly championed for us, getting us with a Cluster that we can use, even though it was not is bread and butter.
@jimpick will more focused on develping Test Plans, starting with #96 and then expanding his scope to think about developer experience, onboarding (docs, demos) and overall, making sure we make writing Test Plans super simple and fun.
For a good handoff, @jimpick please write down a brain dump of:
- Where Infra is today
- Where it needs to be
- What are still some of the open …

Infra Lead Responsibilities Handoff.initiate()

---

Makefile
README.md

1. Updates the makefile to make it more cross-platform (`pip` --> `python -m pip`). The official documentation now [recommends](https://bugs.python.org/issue22295) the latter.
2. Updates the README make command to `make pre-commit`.
License: MIT

docs: fix make command and make makefile cross-platform

---

docs/USAGE.md
sdk/runtime/runenv.go

This adds support for two new different types of test parameters and fixes #195.
1. Array of Strings, through the functions:
- `func StringArrayParam(name string) (a []string, ok bool)`
- `func StringArrayParamD(name string, def []string) []string`
2. And arbitrary JSON structures:
- `func JSONParam(name string, v interface{}) (ok bool)`
---
In reality, `StringArrayParam` and `StringArrayParamD` are just wrappers for `JSONParam`. 
I didn't add `IntArrayParam` nor `BoolArrayParam` because I think they are more uncommon. However, I'm open to see what you've to say!
License: MIT

feat: add support for array of strings and json parameters

---

docs/PLAN_SPEC.md
plans/chew-large-datasets/README.md
plans/data-transfer-datasets-interest/README.md
plans/data-transfer-datasets-random/README.md
plans/dht/README.md
plans/message-delivery/README.md
plans/naming/README.md
plans/nodes-connectivity/README.md
plans/providing-content/README.md

As the plans live independently in seperate directories, it's
okay if some are "work-in-progress" and don't have working
implementations yet.
The levels were borrowed from: https://github.com/ipfs/specs

Add status badges to plans

---

pkg/api/builder.go
pkg/build/golang/Dockerfile.template
pkg/build/golang/deps.go
pkg/build/golang/deps_test.go
pkg/build/golang/docker.go
pkg/build/golang/exec.go

This closes #147. Adds support for tracking the dependency graph changes by adding a new `Dependencies` variable into `BuildOutput`. It contains a map in the format module=>version. It allows for easy checks of versions changes and/or if a module was added/removed.
Note that in Docker mode, if the image is cached, nothing will be printed, and hence the dependencies map will be empty. Not sure if it's supposed to be this way or not, so I'll wait for your feedback!
License: MIT

feat: track dependency tree

---

docs/HOW_WE_WORK.md

Apparently, `ready` often confuses a ton of people as in "PR is ready". Given that `ready` has been used as a synonym for `backlog`, I'm renaming it to the widely accepted term.

rename ready to backlog

---

pkg/aws/ecr.go

We don't have to set AWS credentials when there are other ways to authenticate and get authorisation for a given AWS API.
When `testground` runs as a `daemon` in AWS, the instance itself would have a role, which allows it to query AWS ECR, so we wouldn't have to generate credentials and configure them in the `.env.toml`.
This PR is basically changing the way we create an AWS client, by only using the static credentials if they have been set.

use aws credentials only if set

---

docs/OVERVIEW.md
docs/PLAN_SPEC.md
docs/ROADMAP.md
pkg/daemon/doc.go

This PR closes https://github.com/ipfs/testground/issues/212
@raulk do you think we need more docs on the `daemon`? I think this is just fine for now.

docs: overview section with testground daemon intro

---

Makefile
docs/USAGE.md
pkg/build/golang/docker.go
pkg/docker/container.go
pkg/runner/local_docker.go

Run `make docker-ipfs-testground` to build the docker image locally.
I've modified EnsureContainer() to take a PullImageIfMissing boolean
option - it is set to false for the ipfs/testground image, so it
will not automatically pull it from Docker Hub.
If the image does not exist, it displays the following error:
> Docker image ipfs/testground not found, run `make docker-ipfs-testground`

Add Makefile to build ipfs/testground image (don't pull it)

---

pkg/server/run.go

Flushes local:exec output.
License: MIT

fix: flush local:exec output

---

go.sum
plans/chew-large-datasets/go.mod
plans/chew-large-datasets/main.go
plans/chew-large-datasets/test/ipfs_add_defaults.go
plans/chew-large-datasets/test/ipfs_add_dir_sharding.go
plans/chew-large-datasets/test/ipfs_add_trickle_dag.go
plans/chew-large-datasets/test/ipfs_file_store.go
plans/chew-large-datasets/test/ipfs_mfs.go
plans/chew-large-datasets/test/ipfs_mfs_dir_sharding.go
plans/chew-large-datasets/test/ipfs_url_store.go
plans/chew-large-datasets/utils/create-ipfs-instance.go
plans/chew-large-datasets/utils/testcase.go
sdk/iptb/ensemble.go
sdk/iptb/spec.go

This adds support for custom daemon configuration on IPTB (daemon) tests through a function that modifies the current configuration. I decided to use a function to modify the configuration instead of the configuration itself for some reasons:
1. It's what `CreateIpfsInstance` already does.
2. It easily allows to update the configuration of the IPTB-generated daemon with the command `ipfs config replace`.
Also, this enabled me to add one more test: dir sharding with the daemon! And the CIDs match!

feat: add support for configuration with IPTB & directory sharding test with ext. daemon

---

manifests/chew-large-datasets.toml
pkg/api/definitions.go
pkg/engine/engine.go

Closes #124.
Adds support for a default runner and builder on the manifest.

feat: default runner builder on the manifest

---

plans/chew-datasets/go.mod
plans/chew-datasets/main.go
plans/chew-datasets/test/ipfs_add_defaults.go
plans/chew-datasets/test/ipfs_add_dir_sharding.go
plans/chew-datasets/test/ipfs_add_trickle_dag.go
plans/chew-datasets/test/ipfs_file_store.go
plans/chew-datasets/test/ipfs_mfs.go
plans/chew-datasets/test/ipfs_mfs_dir_sharding.go
plans/chew-datasets/test/ipfs_url_store.go
plans/chew-datasets/utils/metrics.go
plans/chew-datasets/utils/testconfig.go

What the title says!
- Adds metrics for each added file on chew datasets
- Uses runenv.Message instead of fmt.Println/Printf

Add metrics to Chew Datasets and use runenv.Message

---

pkg/engine/engine.go

When there's an error condition, the engine is segfaulting instead of
displaying the error.
To reproduce, force an error by deleting plan/dht/go.mod, and then
build:
```
Dec 12 03:07:34.544927  INFO    listen and serve        {"addr": "[::]:54353"}
Dec 12 03:07:34.551196  DEBUG   handle request  {"ruid": "42aaa4e5", "command": "build"}
Dec 12 03:07:34.620603  DEBUG   request handled {"ruid": "42aaa4e5", "command": "build"}
2019/12/11 19:07:34 http: panic serving [::1]:54354: runtime error: invalid memory address or nil pointer dereference
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc0000dc3c0)
/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1767 +0x139
panic(0x1ab4660, 0x253ab00)
/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2 …
```

Avoid segfault during build time errors

---

pkg/runner/console.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

Panics and other logs go to stderr. We shouldn't try to decode stderr as json.

feat(console): don't decode stderr

---

pkg/runner/local_docker.go

The tests themselves handle timeouts. This timeout was:
1. Too short.
2. Hiding timeout errors from containers themselves.
If we really need one, we can introduce a timeout here later. However, IMO, timeouts should be handled by the user (e.g., with an interrupt).

fix: remove local docker timeout

---

pkg/runner/console.go

* Always use seconds.
* Always print with the same with, right align.
This makes it easier to work with the output.

feat: improve output alignment

---

pkg/runner/cluster_swarm.go

By default calling a network create, creates a network with 24 bit mask, so we can't schedule more than ~256 containers.
This PR is changing the mask to 16 bits.
We also do that at https://github.com/ipfs/testground/blob/master/infra/docker-swarm/ansible/roles/testground-services/tasks/main.yaml#L7

set IPAM for docker swarm service in swarm runner

---

infra/k8s/README-aws.md
infra/k8s/aws/terraform/.gitignore
infra/k8s/aws/terraform/backend.tf
infra/k8s/aws/terraform/backends/example-backend.tf
infra/k8s/aws/terraform/eks-cluster.tf
infra/k8s/aws/terraform/eks-worker-nodes.tf
infra/k8s/aws/terraform/key.tf
infra/k8s/aws/terraform/outputs.tf
infra/k8s/aws/terraform/providers.tf
infra/k8s/aws/terraform/terraform.tfvars-example
infra/k8s/aws/terraform/variables.tf
infra/k8s/aws/terraform/versions.tf
infra/k8s/aws/terraform/vpc.tf

This PR is adding Terraform playbook for creating an AWS EKS cluster.
We haven't decided which orchestrator or cloud we will use for the Testground MVP, but I think it is good to keep our options open and commit the playbooks / setups we are evaluating.

aws eks terraform playbooks

---

pkg/sidecar/docker_instance.go

I don't like this approach, because we get global OS vars from everywhere, and this is already the second place we do it for Redis, but at least this is now configurable and we can fix it in the next days/weeks.

get redis host from env var

---

env-example.toml
pkg/build/golang/docker.go
pkg/config/config.go

This PR is adding DockerHub as an option for Docker Registry.
Ideally we shouldn't use this as we will incur data transfer costs, but this is handy for development, until we set on a specific cloud provider (such as AWS, DO, GCP, etc.)
Ideally we should use an internal registry to the provider we pick - DO or GCP or other.

adding dockerhub registry as an option

---

infra/docker-swarm/ansible/roles/testground-services/tasks/main.yaml
pkg/runner/local_docker.go

This PR is add REDIS_HOST as an ENV VAR when we setup infrastructure for Docker Swarm backend for Testground. Not sure if we will ever use these playbooks, but better keep them accurate when we can.
Related to https://github.com/ipfs/testground/issues/285
--
Regarding other `runners`:
1. `k8s` - REDIS_HOST will be configured within the resource that adds the sidecar to every machine, currently a `daemonset` which is defined at `infra/k8s/sidecar.yaml`
2. `local` ? If we run `testground` locally on Linux, we should be able to start `sidecar` as well. Who does that? Do we have any such scripts or code?

add REDIS_HOST to sidecar

---

.codecov.yml

This makes codecov more tolerant to coverage differences (-5%) so we don't have as many PRs failing at this time.
Borrowed from https://github.com/scikit-learn/scikit-learn/pull/9001/files
License: MIT

chore: do not fail on coverage diff of ~-5%

---

cmd/build.go
cmd/context.go
cmd/daemon.go
cmd/describe.go
cmd/list.go
cmd/run.go
pkg/api/runner.go
pkg/engine/engine.go
pkg/runner/cluster_nomad.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
pkg/server/inproc.go
pkg/server/run.go

This way, we:
* Obey interrupts.
* Cleanup on interrupts.

feat(cmd): use contexts everywhere

---

pkg/tgwriter/tgwriter.go

Fixes #304. New output:
```sh
⟩ ./testground -vv run dht/find-peers \
--builder=exec:go \
--runner=local:exec \
--build-cfg bypass_cache=true \
--instances=10 \
--test-param n_find_peers=5 \
--test-param bucket_size=10 \
--test-param timeout_secs=300
Dec 17 13:38:24.314459	INFO	testground client initialized	{"addr": "localhost:8042"}
engine run error; err: instance count outside (10) of allowable range [16, 10000] for test find-peer
```

tgwriter: append key-values to message.

---

cmd/daemon.go
cmd/itest/common_test.go
pkg/server/server.go

We had a little merge kerfuffle where we merged code that expected Server.Start() to block, with code that didn't. This patch fixes that.

daemon: rename Server.Start() to Serve(), and block.

---

infra/docker-swarm/ansible/.gitignore
infra/docker-swarm/ansible/ansible.cfg-example
infra/docker-swarm/ansible/roles/filebeat/tasks/main.yml
infra/docker-swarm/ansible/roles/swarm-init/tasks/main.yml
infra/docker-swarm/ansible/roles/swarm-join/tasks/main.yml
infra/docker-swarm/ansible/roles/testground-services/tasks/main.yaml
infra/docker-swarm/ansible/roles/testground-sidecar/tasks/main.yaml
infra/docker-swarm/ansible/setup.yaml
infra/docker-swarm/ansible/templates/filebeat.yml.j2

Some Ansible improvements and bug fixes we found today:
1. We can't run `sidecar` as a service, because we need to set up the host process namespace, capabilities, etc. - so we run it as a container.
2. Due to 1, we have to create the overlay network on all worker nodes. This is why we run a dummy `sleep` container to propagate the overlay network to all workers. Docker overlay networks are propagated lazily until a service needs them, and here we need the `control` network in the `sidecar` container.
3. Fix on getting the `Leader` IP - this was racy, and worked only if the leader hadn't added any workers.

fix sidecar container and overlay network

---

pkg/runner/cluster_swarm.go
pkg/runner/cluster_swarm_test.go

This is very hacky and I wouldn't want to merge it, we need to keep track of allocated networks to testplans and get a `free` range when we create a new network.

different address range for every testplan network

---

infra/docker-swarm/ansible/roles/testground-services/tasks/main.yaml
pkg/docker/network.go
pkg/runner/cluster_swarm.go
pkg/runner/common.go
pkg/runner/common_test.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
sdk/runtime/runenv.go
sdk/sync/presets.go

Previously, we did this for docker swarm but not docker local.
This patch also exposes the chosen subnet to the test via the TestSubnet runtime environment variable. That way, the test can easily figure out which network interface is the "data" network and what IP addresses it should use (when asking the sidecar to assign an IP address).
factored out of https://github.com/ipfs/testground/pull/271
(also tested in that PR via the sidecar test)

feat: consistently use predefined network blocks

---

.travis.yml
cmd/itest/run_test.go
cmd/itest/sidecar_test.go
docs/NETWORKING.md
docs/SIDECAR.md
docs/USAGE.md
manifests/network.toml
pkg/sidecar/docker_instance.go
pkg/sidecar/link.go
plans/dht/test/common.go
plans/network/README.md
plans/network/go.mod
plans/network/main.go
sdk/sync/helper.go
sdk/sync/presets.go

* Make it possible to set IP addresses with the sidecar (docker only, may not work in swarm?).
* Document the sidecar.
* Use a consistent subnet for the control network.
* Test the sidecar.
TODO:

Sidecar: add method to set IP addresses

---

.codecov.yml

From the docs, pointed out by @raulk
_informational_
Use Codecov in informational mode. Default is false. If true is specified the resulting status will pass no matter what the coverage is or what other settings are specified. Informational mode is great to use if you want to expose codecov information to other developers in your pull request without necessarily gating PRs on that information.

codecov set informational flag to true

---

plans/network/main.go

This test is very timing dependent. 30ms still demonstrates that the RTT is no longer 200ms.
fixes #325

test(network): fix flaky sidecar test

---

.travis.yml
manifests/dht.toml
plans/dht/test/find_peers.go
plans/dht/test/find_providers.go

This PR is adding compilation of `dht test` as part of CI. We should be doing this for every test that we consider ready and maintained, at least for now, when tests are somewhat part of the `testground` codebase.
It is also fixing the code that gets the runtime config as we no longer have methods with default parameters - they are now taken from the `toml` config.

add dht test plan compilation to tests

---

pkg/docker/container.go

Not sure what `RepoTags` stands for, and even though Docker says it is required:
```
// repo tags
// Required: true
RepoTags []string `json:"RepoTags"`
```
On my machine, `testground` was panicking when running:
`testground -vv run network/ping-pong --builder=docker:go --runner=local:docker`

check len is > 0

---

docs/NETWORKING.md
infra/docker-swarm/ansible/roles/testground-services/tasks/main.yaml
pkg/runner/common.go

Otherwise, we can conflict with the host's _real_ IP addresses.
192.18.... should be safe as it's set aside for testing and benchmarking.

fix: use a different control network

---

pkg/runner/console.go
pkg/runner/eventmanager.go
pkg/runner/filelogger.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

To log to a file add the run-cfg parameter log_file, eg
`$ ./testground run bitswap-tuning/transfer --builder=docker:go --runner=local:docker --build-cfg bypass_cache=true --run-cfg log_file=/tmp/myfile.txt`

Log to a file

---

pkg/sidecar/docker_instance.go

@Stebalien I haven't verified this one, I am focusing on the rest of the issues - probably worth running it, before we merge it (unless you are confident enough that this is a bug).
---
TODO:

use cfg.Network instead of netId

---

infra/k8s/README.md

I think this paragraph doesn't really belong in the `infra` docs. Also now we are back to AWS, so we can easily use the AWS ECR registry, which should be faster than Docker Hub.
I don't like that the commands are not directly runnable on user's machines, as I am referring to Docker Hub still, so there is still room for improvement there, and `docs` still assume some familiarity with Testground daemon/client configuration.

remove Docker Hub paragraph

---

manifests/bitswap-tuning.toml
plans/bitswap-tuning/test/transfer.go
plans/bitswap-tuning/utils/net.go

Allows client to set latency and bandwidth as test parameters

Traffic shaping for bitswap plan

---

infra/k8s/README.md
infra/k8s/kops-weave/dummy.yml
pkg/runner/cluster_k8s.go

Apparently we must have at least one pod , so that we get an IP address from the default k8s networking (Flannel), so that interface `cni0` is created.
We used this `cni0` interface later in the `initContainer` in `weave.yml` to add a route to all workers so that they can reach the services Kubernetes network (`redis-master`, etc.).

add dummy daemonset

---

infra/k8s/README.md

This PR adds a few edits to the k8s README to include some missing install steps and directory paths.
Note that with respect to the future improvement:
> We need to decide where Testground is going to publish built docker images - DockerHub? or? This might incur a lot of costs if you build a large image and download it from 100 VMs repeatedly.
One of our partners is trying to solve a very similar problem by using IPFS :)

Edits to k8s README

---

infra/k8s/kops-weave/weave.yml
infra/k8s/sidecar.yaml
manifests/dht.toml
pkg/build/golang/Dockerfile.template
pkg/runner/cluster_k8s.go

Something is wrong with the current k8s-sidecar runner. Network for `redis-master` (the control network) was not reachable in the `dht/find-peers` test when running the k8s-sidecar runner from `master`.
Resolution:
This is expected actually, because we do not have route for 100.64 services CIDR, we only have route to pod IPs.
---
This is just a heads-up for @dirkmc that you have to use `nonsens3/testground` (which has routes removal part disabled), in case you want to try `sidecar` with k8s today.
Will write follow up when I understand why `redis-master` is not reachable when we remove the routes - this should not be the case.

update redis endpoint from `redis-master` to `redis-headless`

---

plans/dht/test/common.go

Currently all bootstrap nodes will dial each other. This can lead to simultaneous connection issues within libp2p where both bootstrappers end up dropping their connections to each other.
The solution used here is to have bootstrappers only dial those bootstrappers with peerIDs lexicographically than them.

DHT plan: avoid simultaneous connect issues with bootstrappers 

---

pkg/runner/cluster_k8s.go

Running `testground` on a k8s cluster and passing in `--run-cfg keep_service=false` doesn't delete the batch job when a timeout occurs:
```
testground --vv run network/ping-pong \
--builder=docker:go \
--runner=cluster:k8s \
--build-cfg bypass_cache=true \
--build-cfg push_registry=true \
--build-cfg registry_type=aws \
--run-cfg keep_service=false \
--instances=2
```
results in 
```
Jan 23 17:43:05.114810  WARN    engine run error        {"ruid": "921b8bcd", "err": "timeout"}
```
Attempting to run the same test again, we get an error about existing `jobs.batch "tg-network"`
```
Jan 23 17:47:06.776730  WARN    engine run error        {"ruid": "3e3823e9", "err": "jobs.batch \"tg-network\" already exists"}
``` 
This moves the `defer` function to run before the for loop to ensure that job …

Ensure k8s jobs get deleted when `keep_service=false`

---

pkg/runner/eventmanager.go
plans/bitswap-tuning/main.go
plans/bitswap-tuning/test/transfer.go
plans/chew-datasets/main.go
plans/chew-datasets/test/ipfs_add_defaults.go
plans/chew-datasets/test/ipfs_add_dir_sharding.go
plans/chew-datasets/test/ipfs_add_trickle_dag.go
plans/chew-datasets/test/ipfs_file_store.go
plans/chew-datasets/test/ipfs_mfs.go
plans/chew-datasets/test/ipfs_mfs_dir_sharding.go
plans/chew-datasets/test/ipfs_url_store.go
plans/chew-datasets/utils/testcase.go
plans/dht/main.go
plans/dht/test/common.go
plans/dht/test/find_peers.go
plans/dht/test/find_providers.go
plans/dht/test/provide_stress.go
plans/dht/test/store_get_value.go
plans/network/main.go
plans/placebo/main.go
plans/smlbench/test/simple_add.go
plans/smlbench/test/simple_add_get.go
plans/smlbench/utils/testcase.go
sdk/runtime/output.go
sdk/runtime/runner.go

Mainly, return values from tests and drop `runtime.Abort` and `runtime.OK`.
1. We always just call OK at the end of the test so this is pretty useless.
2. We keep calling `Abort` then continuing with the test. An alternative here would be to make `Abort` _panic_. However, it's probably simpler to just return from the test.
Additionally, this change catches panics and returns stack traces in the structured logs.
This isn't a critical change, it has just been bugging me a bit and it was relatively simple to implement (for now, at least).

feat: refactor result status handling

---

infra/k8s/README.md
infra/k8s/redis-values.yaml
pkg/sidecar/k8s_instance.go

I had royally fucked up the `routes` adding and removal, probably it was working by coincidence, due to the small cluster that these were initially developed on.
I am not happy with the current state of `manageContainer`, but at least this is working now:
Routes on a `testplan` container start as:
```
default via 100.96.5.1 dev eth0
100.96.0.0/16 via 100.96.5.1 dev eth0
100.96.5.0/24 dev eth0 proto kernel scope link src 100.96.5.253
```
and become the following after we attach the `data` network:
```
default via 20.0.0.0 dev eth1
20.0.0.0 dev eth1 scope link
24.171.0.0/16 dev eth1 proto kernel scope link src 24.171.64.0
100.64.0.10 via 100.96.5.1 dev eth0
100.96.4.3 via 100.96.5.1 dev eth0
```
You can see that `100.96.0.0/16` is restricted to just redis at `100.96.4.3`, and we also have …

fix k8s_instance.go runner to remove routes

---

Makefile

This causes executable to land in $HOME/.local/bin/
No root user required.

Pip install to homedir

---

infra/k8s/redis-values.yaml
pkg/sidecar/k8s_instance.go

This is solving the issue of Kubernetes killing on occasion containers due to it not able to get a pod IP:
```
Jan 24 14:23:19 ip-172-20-43-110 kubelet[18017]: W0124 14:23:19.263257   18017 docker_sandbox.go:394] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "tg-dht-17_default": unexpected address output
Jan 24 14:23:19 ip-172-20-43-110 kubelet[18017]: I0124 14:23:19.266469   18017 kuberuntime_manager.go:454] Sandbox for pod "tg-dht-17_default(a5352449-3888-4da3-95ad-540f02760d7e)" has no IP address. Need to start a new one
```
I assume that `sidecar` has restricted the container network, before the `pod` to which this container belongs had a chance to get to `Ready` state.
Obviously this is a hack and `time.Sleep` is not reliable, but I …

sidecar race with kubernetes and CNI

---

cmd/sidecar.go
pkg/dockermanager/dockermanager.go
pkg/runner/eventmanager.go
pkg/runner/local_docker.go
pkg/sidecar/docker_instance.go
pkg/sidecar/docker_logs.go
pkg/sidecar/instance.go
pkg/sidecar/k8s_instance.go
pkg/sidecar/other.go
pkg/sidecar/sidecar.go
plans/network/main.go
sdk/runtime/runenv.go

* Mount an assets directory in test containers for persisting assets.
* Use the sidecar to write stderr/stdout to the each test instance's asset directory.
Currently, we put all this in the "work directory" under "results". I.e., `~/.testground/results/$testplan/$runid/$container_hostname/`.
At the moment, this is configured for local docker only. On K8S, we should mount the same S3 bucket on each host then mount that S3 bucket inside the sidecar and each test instance.
Note: I've also removed the log_file option from the docker runner. That's no longer useful given that we store test results.
part of #377

persist assets and logs

---

infra/k8s/README.md
plans/dht/test/common.go

Fixes: https://github.com/ipfs/testground/issues/417
With this, I see only up to 2 attempts in the logs, and not 5, so it looks like the 2nd attempt is successful.
However the `dht/find-peers` testplan is still not successful:
```
{"runenv":{"test_plan":"dht","test_case":"find-peers","test_run":"974fd68b-b6ac-4a1b-9b11-04c7a6616bd0","test_seq":0,"test_instance_count":840,"test_instance_params":{"auto_refresh":"\"true\"","bucket_size":"2","n_bootstrap":"1","n_find_peers":"1","random_walk":"\"false\"","timeout_secs":"300"},"test_sidecar":true,"test_network":{"IP":"17.87.0.0","Mask":"//8AAA=="}},"timestamp":1580221453306736283,"result":{"outcome":"aborted","reason":"context deadline exceeded waiting on bootstrap-connected; not enough elements, required: 840, got: 838"}}
```

Increase retry timeout

---

.codecov.yml

Apparently, the informational flag on Codecov is not working as we expect it to, i.e., not to fail when there are negative changes in the coverage.
My idea is to just change the threshold to 100%. This param is:
> Allow the coverage to drop by X%, and posting a success status.
Closes #321.

chore: do not fail on negative cov difference

---

pkg/sidecar/docker_logs.go

`dockerLogs` is a private struct that is only used in the linux host, it's file should be linux build only as is the rest of the sidecar package. Since we have git commit hooks that run the linter this is required to make commits on Windows succeed.
@Stebalien should I enable the linter for the Windows CI to prevent this in the future or is the cost not worth it?

Only build Docker logs on linux

---

cmd/all.go
cmd/build.go
cmd/itest/build_test.go
cmd/itest/run_test.go
cmd/itest/sidecar_test.go
cmd/run.go
docs/COMPOSITIONS.md
pkg/api/composition.go
pkg/engine/engine.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

* Validate compositions appropriately based on context: is it a build or a run?
* Migrate `builder` and `runner` flags to normal string flags. The previous logic leaked, as runners and builders are maintained and operated on the daemon side, and the client should not instantiate an engine.
* Adjust `cmd/itests` to use the `single` variant of build and run commands; also to pass in the instance count.
* Mutex to avoid concurrent initialisations of the `local:docker` runner.
---
Note: `TestSidecar` times out, but it also did in master previous to merging compositions.

compositions: follow-up fixes

---

infra/k8s/sidecar.yaml

Fixes https://github.com/ipfs/testground/issues/416
Now the `initContainer` on `sidecar` daemon, won't start until `cni0` is available. `cni0` is created by the first pod on every host, which attaches to the default k8s network (flannel) - in the current setup that would be the `s3bucket` daemon.

fix k8s autoscaling and proper initialisation of all daemonsets

---

pkg/build/golang/docker.go
pkg/runner/local_docker.go

E.g., this might be set via DOCKER_HOST.
Note: If we're using a TCP socket, we still guess /var/run/docker.sock. In that case, we might be running on another machine. We could probably get smarter about this, but this is likely good enough.

fix: use the auto-detected local:docker socket location

---

infra/k8s/kops-weave/s3bucket.yml

I've added an `automated build` to Docker Hub, so this will be rebuilt on every commit to master based on Dockerfile at `infra/k8s/s3fs/`.

use ipfs/testground:s3fs image

---

pkg/engine/engine.go
pkg/runner/cluster_k8s.go

I think it is nicer to use a shorter runid for test plans, because then we don't have gigantic folder name, pod names, etc.
12 characters with an alphabet of 26+10 is enough entropy IMO.
---
Also adding the `RunID` as part of pod name, so that we can run multiple testplans and also use `keep_service=true`.

use shorter runid

---

README.md
docs/COMPOSITIONS.md
docs/USAGE.md

This PR is fixing a bit the USAGE docs, which are linked from the main page of Testground - https://github.com/ipfs/testground/
1. I remove the reference to `SPEC.md`, which is the first thing that we tell users in the `USAGE` section. The `SPEC.md` is rather outdated, so it is very misleading to tell that to users in their first step. Furthermore `SPEC.md` is linked from the main page, right below the link to `USAGE` - no need to add the same link at multiple high-profile places.
2. Removed the reference to the automatic daemon that we used to start - we haven't done that for a while, so probably no-one cares (unless someone runs a commit from 2 months ago, which I doubt).
3. Remove the sample `run` command which is in the section that explains the Testground environment - it is …

improved usage docs

---

infra/k8s/sidecar.yaml

This PR is adding a check requiring redis to be running before we start sidecar.
It makes it possible to install all testground services at the same time without them crashing.

sidecar installation - wait for redis

---

pkg/sidecar/k8s_instance.go

This is expected to happen, due to us iterating over the routes, so downgrading the `warning` to a `debug` line.

downgrade warning

---

infra/k8s/README.md
infra/k8s/install.sh

This PR is adding an `install.sh` script which goes through all the steps from creating the cluster to the installation of Testground dependencies.
If you have a `cluster.yaml` file, you only have to set the ENV variables (ideally in your .rc file) and have a one-command to start and later destroy the cluster.
---
Also added a note on how to `resize` the cluster in case you figure out that you need more or less machines than originally planned.
---
On my end it takes 6:30min for the cluster to be ready:
```
Testground cluster is ready
Execution time was 383 seconds
```

improved installation process

---

pkg/daemon/run.go
pkg/runner/cluster_k8s.go
pkg/sidecar/k8s_instance.go
sdk/runtime/runenv.go

use folder with index name ; sidecar should not logs to /outputs ; toNet should not panic

---

go.mod
sdk/iptb/go.mod
sdk/sync/go.mod

Inter-dependent submodules suck in go. We're hoping for the best here.

release/0.1.0: update go.mod files.

---

go.sum
pkg/build/golang/docker.go

Without this, I get the follow error:
```
Feb  7 12:53:01.542683  INFO    tagging image   {"build_id": "726669436b8b", "tag": "909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht:726669436b8b"}
Feb  7 12:53:01.552942  INFO    pushing image   {"build_id": "726669436b8b", "uri": "909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht"}
The push refers to repository [909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht]
Feb  7 12:53:01.949627  INFO    build failed    {"plan": "dht", "group": "single", "builder": "docker:go", "error": "tag does not exist: 909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht:latest"}
Feb  7 12:53:01.949683  WARN    engine build error: tag does not exist: 909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht:latest …
```

fix pushing image to remote (aws ecr)

---

README.md

The double space before the primary scoped bullet prevents the sub-bullet from indenting for the IPTB project description. This subtle change allows for proper indention in the README.

docs: Fix IPTB project description bulleting in README

---

pkg/runner/cluster_k8s.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
sdk/runtime/logger.go
sdk/runtime/output.go
sdk/runtime/runenv.go
sdk/sync/redis_test.go

The RunEnv is for the testcase and needs an initialized logger, etc. The run params are just data.
This prevents us from, e.g., calling functions that try to access uninitialized fields. This _also_ lets test cases (e.g., the redis test cases) safely construct fully initialized run environments.

feat: distinguish between runenv and run params

---

pkg/sidecar/docker_instance.go
sdk/runtime/runenv.go

Instead of parsing the environment, modifying it, then re-serializing it; parse it without constructing a runenv, modify it, then construct a runenv.
fixes https://github.com/ipfs/testground/pull/502#pullrequestreview-355481906

fix: remove a runenv hack in the sidecar

---

env-example.toml
infra/k8s/README.md
infra/k8s/install.sh
pkg/api/runner.go
pkg/engine/engine.go
pkg/runner/cluster_k8s.go

Fixes: https://github.com/ipfs/testground/issues/480
---
I think based on the new docs, it should be mostly clear to folks outside PL that they have to provide credentials for an S3 bucket, if they want to create a Kubernetes environment.

extract outputs configs to toml configuration

---

sdk/sync/redis_test.go
sdk/sync/watch.go

Otherwise, we'll leak a goroutine if the user has walked away.
Also, make sure canceling the context actually cancels the barrier (test).

buffer barrier channel

---

pkg/runner/cluster_k8s.go

A simple check before we try to schedule pods to Kubernetes to make sure we have enough resources.
If we don't do that and a user requests 1000 pods, and has for example only 3-4 workers, then pods would go into `Pending` state, and wait for available resources, which will never come as we currently don't have auto-scaling.
---
Fixes: https://github.com/ipfs/testground/issues/498
---
TODO:

max allowed pods check in cluster_k8s.go

---

cmd/run.go

Fixes: https://github.com/ipfs/testground/issues/520
---
Cross posting from another PR:
It currently takes almost 2 min to download assets with `--collect` for run `9ccc44f28b15` (~2k small files), whereas downloading with `aws s3 cp --recursive` takes 10 seconds.
Maybe we should refactor this to first download and then zip, rather than be forced to download sequentially. WDYT ?

--collect and --collect-file flags

---

infra/k8s/README.md
infra/k8s/install.sh
infra/k8s/kops-weave/s3bucket.yml

Fixes: https://github.com/ipfs/testground/issues/537
---
Region and endpoint are not technically a secret, but we are keeping all the configs for the S3 bucket at one place.
@aschmahmann for your env, this looks like:
```
2020-02-12 10:51:30         21 assets_adin_access_key
2020-02-12 10:51:44         22 assets_adin_bucket_name
2020-02-12 14:52:59         39 assets_adin_s3_endpoint
2020-02-12 10:51:38         41 assets_adin_secret_key
```
So the `export` calls are slightly different.

extract S3_ENDPOINT in var, so that we can change region for bucket

---

infra/k8s/s3fs/Dockerfile.s3fs

Probably best building v1.86 every time, than picking up `master` from `s3fs-fuse` when we merge to `master`.

set s3fs version in Dockerfile

---

sdk/sync/watch.go

Seen while debugging with @aschmahmann.
1. Differentiate between a context cancellation and a context deadline expiring.
2. Fail early and clearly when we get too _many_ elements.

Improve two barrier related errors

---

infra/k8s/README.md
infra/k8s/install.sh

Fixes: https://github.com/ipfs/testground/issues/550
---
With this, if we need to log to another cluster, we just have to update the context for the local kubectl client with:
```
kops export kubecfg --state $KOPS_STATE_STORE --name=$NAME
```
And then we already have the SSH keys to log to the hosts.

use shared ssh key for kops hosts ; command to extract kube context

---

cmd/all.go
cmd/terminate.go
pkg/api/engine.go
pkg/api/runner.go
pkg/client/client.go
pkg/client/types.go
pkg/daemon/daemon.go
pkg/daemon/terminate.go
pkg/engine/engine.go

This is related to #432 and adds the `terminate` command and the `Terminatable` interface.
I decided to do this on smaller PRs.
On this PR:
- A single-method interface Terminatable: TerminateAll() error that runners supporting termination can implement.
What's missing to do on separate PRs:
- Implement `TerminateAll() error` for each runner.
License: MIT

feat: terminate command and interfaces

---

pkg/runner/cluster_k8s.go

This is simplifying the signature for most methods in the Kubernetes runner, by pushing the Kubernetes related APIs to the runner itself, rather than providing them as function arguments all the time.

refactor k8s cluster runner

---

cmd/sidecar.go
infra/k8s/sidecar.yaml

TODO:
We could template this, so that a dev can enable/disable pprof, but for now we can assume that `sidecar.yaml` is setup correctly (enabled or disabled) and be done with it - I don't want to introduce another level of indirection.
---
Fixes: https://github.com/ipfs/testground/issues/423

expose pprof port on sidecar

---

pkg/build/golang/docker.go

Adin reported the following failure:
```
Feb 12 11:01:41.601217  INFO    build succeeded {"plan": "dht", "group": "balsa", "builder": "docker:go", "artifact": "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-dht:708f550fefe8"}
Feb 12 11:01:41.603198  WARN    engine build error: RepositoryAlreadyExistsException: The repository with name 'testground-dht' already exists in the registry with id '909427826938'     {"ruid": "1f1fce89"}
```
It looks like AWS ECR is complaining that a repo already exists in the registry 909427826938 - now this is a bit ambigious, as we have this registry currently in at least 2 regions:
1. `909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-dht`
2. `909427826938.dkr.ecr.eu-central-1.amazonaws.com/testground-dht`
If there is indeed a problem with …

aws ecr repo should probably be unique across regions

---

cmd/run.go
pkg/runner/cluster_k8s.go
sdk/sync/helper.go

This is prerequisite for the k8s<->sidecar coordination, so that at least I can see that after getting rid of the 20sec. we still initialise correctly all networks, rather than have to review all logs (sidecar) across clusters.

measure when testground is ready and testplans are running

---

docs/EVOLVING_APIs.md

This design proposal:
* analyses the problem domain.
* studies various tactics and their applicability in the face of different kinds of upstream API evolution.
* proposes a concrete solution for both manual shim activation, and automatic shim activation based on version detection.

Proposal: dealing with upstream API evolution in test plans

---

sdk/sync/common.go
sdk/sync/redis_test.go
sdk/sync/watch.go
sdk/sync/write.go

The redis client is designed to be shared between many goroutines. We were creating separate redis instances everywhere. This meant:
1. Each test instance created two redis clients instead of one (write & watch).
2. The sidecar created two redis clients (and multiple connections) per test instance.
Worse, we weren't _closing_ writers. That meant we were leaking connections on the sidecar. This change sidesteps that problem by just sharing connections everywhere.

feat(sync): use a shared redis client

---

sdk/sync/subscription.go

Even if the user hasn't canceled the subscription's context.

fix(sync): cancel all subscriptions when closing the watcher

---

infra/k8s/README.md
infra/k8s/cluster.yaml.example_with_monitoring
infra/k8s/install.sh

This is a cluster.yaml which has been edited to enable cluster monitoring with Prometheus
This might fix: https://github.com/ipfs/testground/issues/228
The idea here is to include a cluster.yaml rather than generating it with kops create and making small edits, as currently prescribed in the README. This version includes edits necessary to add host monitoring and enables testground users to observe how the cluster nodes are performing.

Example cluster.yaml

---

infra/k8s/redis-values.yaml

A short-term hack to make sure that Redis is using a full c5.2xlarge machine.
If we don't do that, requests to Redis time out, because the testplan instances on that VM starve it.
We should review what is the best way to run Redis - for example I know it is single-threaded, so having multiple cores, doesn't really help it, unless we run multiple instances. This is out of scope for now.

adjust redis config

---

sdk/sync/subscription.go

If we stop the watcher before we cancel subscriptions, the watcher's "close" channel will be closed but the subscription's context won't be canceled. Handle this case.
fixes #601

fix(sync): avoid logging spurious errors when we shutdown the watcher

---

pkg/docker/container.go

Bug:
When container is already running, I see an error that the container cannot be created because it already exists.
With this fix, we the following messages in different scenarios:
When the container is killed:
```
Feb 28 18:04:00.794792	INFO	performing build for group	{"plan": "example", "group": "single", "builder": "docker:go"}
Feb 28 18:04:00.797107	INFO	found existing volume	{"build_id": "1c0765d9484c", "volume_name": "testground-goproxy-vol"}
Feb 28 18:04:00.798812	INFO	container isn't running; starting	{"build_id": "1c0765d9484c", "container_name": "testground-goproxy"}
Feb 28 18:04:04.756539	INFO	build succeeded	{"plan": "example", "group": "single", "builder": "docker:go", "artifact": "1c0765d9484c"}
```
When the container is deleted:
```
Feb 28 18:04:17.590620	INFO	performing …
```

handle already running containers

---

pkg/dockermanager/dockermanager.go
pkg/sidecar/k8s_instance.go

Fixes: https://github.com/ipfs/testground/issues/414
This is supposed to fix the `time.Sleep` hack I introduced a while ago, so that we make sure that Kubernetes is done getting a `PodIP`, before we mess with container networking with `sidecar`.
This PR makes the assumption that it is `safe` to change the networking after a container is in `Running` phase. I am not 100% sure that Kubernetes is done getting the `PodIP` at that stage, but it probably it.

remove time.Sleep; fix coordination between k8s-sidecar

---

pkg/runner/cluster_k8s.go

The k8s runner is initialized during the first Run().
Until there has been at least a single run, c.pool is a null pointer.
I hadn't seen this before, but this causes an exception to be raised if a terminate command is run
prior to running any jobs.
With this patch, a new pool is created, to avoid the problem of having an unitialized runner.

BUG: null pointer accessing pool.

---

dashboards/example.json

Add example dashboards.
This is just to show a few options to inspire plan developers to write dashboards.
This dashboard uses the metrics collected from example/prometheus2, and creates a dashboard that looks something like this:

Add example dashboard

---

manifests/bitswap-tuning.toml
plans/bitswap-tuning/suites/common.js
plans/bitswap-tuning/suites/version-compat/aggregate.js
plans/bitswap-tuning/suites/version-compat/chart.js
plans/bitswap-tuning/suites/version-compat/defs/one-leech-two-seeds.js
plans/bitswap-tuning/suites/version-compat/gentomls.js
plans/bitswap-tuning/suites/version-compat/run.sh
plans/bitswap-tuning/test/transfer.go
plans/bitswap-tuning/utils/metrics.go
plans/bitswap-tuning/utils/net.go

Fixes https://github.com/ipfs/testground/issues/435
Test plan to verify that new bitswap can pull from old bitswap nodes.
This plan creates a leech pulling from two seed nodes, where each seed has two thirds of the blocks. The leech / seed combinations are:
- old <- two old
- master <- two master
- master <- two old
- master <- one old & one master
As expected, it appears that master fetching from old bitswap nodes performs slightly more slowly than an old bitswap node fetching from old bitswap nodes (because old bitswap nodes don't support the DONT_HAVE message so it must be simulated with timeouts). 
However master does appear to be more consistent - note the cluster of red points at 32MB, showing that when an old bitswap leech pulls from two old bitswap seeds it is slow for that file …

Bitswap tuning version compatibility plan

---

manifests/benchmarks.toml
plans/benchmarks/benchmarks.go
sdk/runtime/runner.go

* yield from the pusher goroutine when closing.
* barrier test case: make iteration count a test param.
* barrier test case: anonymous type for config.

baseline test: fix minor issues

---

manifests/example.toml
plans/example/go.mod
plans/example/main.go
plans/example/prometheus_3.go

This PR is adding a set of very simple measurements:
1. Counter that gets incremented once every 2 seconds.
2. Three stages with 100 calls to a function that has latency around 100ms, 200ms and 500ms
We should have an example dashboard on how to visualise those, so that developers using Testground know how to use the `runenv` metrics SDK and how to visualise the results.
cc @coryschwartz

example measurements - counters and timers

---

sdk/runtime/output.go

fixes an inverted nil check for the `TestSubnet` param

Fix inverted nil check in RunParams.MarshalLogObject

---

manifests/placebo.toml
plans/placebo/main.go
sdk/runtime/runner.go

Fixes https://github.com/ipfs/testground/issues/674.

ensure panics make it to std.err output artifact.

---

pkg/docker/output.go

Don't try to send fancy terminal output.
1. It doesn't work that well. Docker command output is sometimes multi-line progress bars, which get squashed when output the way we print it now.
2. Even if it did work well, we might not want it. The output should be scroll-able -- more like a log, and should not include terminal escape sequences, cursor movements, beeps, colors, clears, etc.

dont be a terminal

---

go.sum
infra/docker/README.md
infra/docker/testground-prometheus/Dockerfile
infra/docker/testground-prometheus/prometheus.yml
pkg/docker/image.go
pkg/runner/local_docker.go
pkg/sidecar/docker_reactor.go

This is not yet complete, but you can see where it's going.
The prometheus endpoint comes pre-configured with a scraper for the pushgateway, just like it does with the prometheus-operator on kuberntes. It accomplishes this by building a new image with the desired configuration built in.
This builds upon https://github.com/ipfs/testground/pull/681 and depends on it.
Right now there's something I'm doing something wrong with setting up the routes, and I'll have to fix that later.
issue: https://github.com/ipfs/testground/issues/660

local docker prometheus

---

infra/k8s/README.md

Since we moved away from assets being stored on S3 to EFS, we no longer need this.

infra/k8s: remove ASSETS_S3 vars

---

Dockerfile
go.mod
go.sum
pkg/runner/local_docker.go
sdk/sync/common.go
sdk/sync/go.mod
sdk/sync/go.sum
sdk/sync/redis_bench_test.go
sdk/sync/redis_test.go

Fixes https://github.com/ipfs/testground/issues/708.
* increase default sync service redis pool size from `runtime.NumCPU()*10` (default) to `8192` to prevent starvation.
* Starvation is very probable in the sidecar, given that we use the XREAD primitive, which blocks a connection.
* The sidecar is especially exposed to this, as it is a single process that accumulates a lot of `XREAD` blocked conns to receive network change requests from instances.
* `8192` is a suitable value because on `local:docker`, we won't run as many containers, and on `cluster:k8s`, sidecars only handle containers colocated on the node.
* increase ulimits on infra containers to 1M open file descriptors.
* expose pprof port of sidecar; enable GC traces for debuggability.
* upgrade to go-redis v7.2.0.
additionally: …

harden redis and sync service.

---

infra/k8s/install.sh

If you have specified the ~~AWS_ZONE~~ AWS_REGION to something other than the default, kops will create the cluster that is undetectable later. Lets specify --region on all aws commands.

Explicit AWS region in install script

---

pkg/build/golang/docker.go

These 2 steps are rather important for our feedback loop, so it'd be nice to log how long they take and build intuition in case something is wrong, once we start building more complex compositions.

add build and push step timers

---

pkg/runner/cluster_k8s.go

Currently for `cluster:k8s` we create a tar with the `/outputs/RUN_ID/COMPOSITION/...` structure, whereas other runners create it with `/RUN_ID/COMPOSITION/...`.
This PR is fixing this.

consistent path for testground outputs

---

sdk/sync/watch.go

See https://github.com/ipfs/testground/issues/663#issuecomment-601156701.

sync: barriers - decrease polling frequency to 1s.

---

pkg/runner/cluster_k8s.go

`g` is currently not shadowed, so the closures use incorrect group, resulting in wrong `OUTPUTS` path env var and wrong calls to `kubectl get logs`.
---
I never noticed that because locally I test with a single group, this was noticed by @aschmahmann when running a composition with multiple groups.

shadow group var

---

infra/k8s/install.sh

Currently after creating a cluster from `install.sh` we get:
```
NAME                                      READY   STATUS                       RESTARTS   AGE
dummy-5z8rk                               1/1     Running                      0          11m
dummy-kr6n2                               1/1     Running                      0          11m
dummy-rq45d                               1/1     Running                      0          11m
efs-provisioner-67884fbc9-8jzzm           1/1     Running                      0          11m
prometheus-pushgateway-77c74c469d-z2r85   1/1     Running                      0          10m
redis-master-0                            2/2     Running                      0          10m
s3bucket-lgrpr                            0/1     CreateContainerConfigError …
```

k8s: remove s3 bucket pod

---

infra/k8s/kops-weave/dummy.yml

This is disabling THP, as we are running Redis on one of these hosts:
```
1:M 20 Mar 2020 12:55:31.928 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

disable transparent huge pages support in kernel

---

docs/USAGE.md
pkg/runner/local_exec.go

Final fix for https://github.com/ipfs/testground/issues/660
healthchecks, with fixes for the prometheus and pushgateway added to the local:exec runner.
I tried to lay this out so it would be less repetitive to add more checks if needed in the future.
First time running (so they all need to be fixed):
```
↬ ./testground healthcheck --runner local:exec
Mar 18 05:28:34.409635	INFO	testground client initialized	{"addr": "localhost:8080"}
checking runner local:exec
finished checking runner local:exec
Checks:
- local-redis: ok; local-redis instance check: OK
- local-prometheus: ok; local-prometheus instance check: OK
- local-pushgateway: ok; local-pushgateway instance check: OK
Fixes:
- local-redis: ok; local-redis instance check: OK
- local-prometheus: ok; local-prometheus instance check: OK
- …
```

local exec healthchecks

---

infra/docker/testground-prometheus/Dockerfile
infra/docker/testground-prometheus/prometheus.yml
pkg/docker/image.go
pkg/runner/local_docker.go
plans/benchmarks/benchmarks.go
plans/dht/test/barrier.go
plans/example/prometheus.go
plans/example/prometheus_3.go
sdk/runtime/metrics.go
sdk/runtime/runenv.go
sdk/runtime/runner.go
sdk/sync/go.mod
sdk/sync/subscription.go
sdk/sync/watch.go
sdk/sync/write.go

This PR:
- refactors the runtime metrics API to make it stem from the runenv: `runenv.M().NewGauge()`.
- modifies the API to tackle Prometheus Opts objects directly, for better flexibility.
- adds CounterVec, GaugeVec, HistogramVec, SummaryVec metrics.
- fixes the Prometheus docker image.
- fixes the Pushgateway liveness check, which got borked in https://github.com/ipfs/testground/commit/c0400ff614dee308e895ccfed3da386d7a385e37#diff-fbfb6e457d5f040c52788ffb0b2a7085R154-R157.
- adds metrics to the sync service, to both the Writer and the Watcher, to monitor barrier and subtree metrics. See #727 for more info.

sync service: add Prometheus metrics, refactor metrics, fix related stuff

---

cmd/itest/sidecar_test.go

`TestSidecar` is flaky, we have a bug issue for it for a while: https://github.com/ipfs/testground/issues/325

disable TestSidecar

---

infra/k8s/cluster.yaml

This is increasing the timeout for idle connection when doing `kubectl port-forward` - you've probably noticed that the connection to Grafana (and now to `testground daemon` when we start deploying in on k8s) gets killed often - this is most probably why.
Related: https://stackoverflow.com/questions/47484312/kubectl-port-forwarding-timeout-issue

increase port-forward timeout in kubelet

---

infra/k8s/install.sh
infra/k8s/testground-infra/values.yaml

See `docs/NETWORKING.md`
control network -> flannel
data network -> weave
Generally we should not add auxiliary services to the data network - it is used by the test plans.

move testground services to control network

---

infra/k8s/README.md
infra/k8s/testground-infra/values.yaml

After merging https://github.com/ipfs/testground/pull/723 there were a few issues noticed.
This PR will restore redis values modifications that were lost when I moved redis into a subchart of the testground-infra chart.

[bug]restore redis values

---

pkg/rpc/writer.go

quickfix. 
CI was failing for a pointer error, and it was a problem with the Discard output writer.

CI fails for pointer error

---

infra/k8s/testground-infra/values.yaml

Not sure if this will be good enough to support 10k instances, but it is better than the defaults:
```
Requests:
cpu:        100m
```

bump up resource requests for pushgateway

---

infra/k8s/efs/manifest.yaml.spec

An attempt to fix https://github.com/ipfs/testground/issues/732
---
It doesn't however fix it, but the `efs-provisioner` container ends up on the `flannel` network:
```
efs-provisioner-65c9486f47-q6khv                       1/1     Running   0          6m55s   100.96.9.3      ip-172-20-36-207.eu-central-1.compute.internal   <none>           <none>
```

set efs-provisioner on flannel network

---

pkg/engine/engine.go
pkg/runner/cluster_k8s.go
pkg/runner/local_docker.go

* fix incorrect messages.
* log when we're performing a healthcheck as part of a build or run.
* print kops output when healthcheck fails.

miscellaneous fixes

---

infra/k8s/kops-weave/genie-plugin.yaml

Another attempt to fix #732 - I am not sure at the time of the creation of the pod, to which network we are attached so that DNS resolution fails. I wouldn't be surprised if this is Weave.
---
In any case we want `flannel` to be the default network so that we don't add `podAnnotations` to every single resource we install on Kubernetes.
---
What confused me about the default network under CNI-Genie is that on Kubernetes, the first file alphanumerically to appear under `/etc/cni/net.d/` is picked up by Kubernetes as the default CNI plugin. I was somehow under the impression that then CNI-Genie would pick up the first alphanumeric plugin (which would be flannel), but this is not the case, and obviously the meta CNI plugin can pick whichever it wants.

cnigenie: add flannel as default network

---

cmd/collect.go
cmd/run.go

`collect` is still broken when called from `testground run ... --collect`.

collect cmd: fix when run as --collect

---

sdk/sync/watch.go

This allows users to build more synchronisation primitives besides CountDownLatches/WaitGroups on top of Barriers, like semaphores.
cc @aschmahmann

sync/sdk: make Barrier lenient by not failing if value > target.

---

infra/k8s/cluster.yaml
infra/k8s/kops-weave/dummy.yml

Fix: https://github.com/ipfs/testground/issues/767
disable transparent-hugepages earlier.
This kops hook creates a systemd unit file which looks like this:
```
[Unit]
Description=Kops Hook disable-transparent-hugepages.service
Before=docker.service
Before=kubelet.service
[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo never >/sys/kernel/mm/transparent_hugepage/enabled"
```
We can see that it works:
```
always madvise [never]
```

disable transparent hugepages earlier (kubernetes)

---

pkg/runner/local_docker.go

Maybe fix: https://github.com/ipfs/testground/issues/691
If https://github.com/ipfs/testground/pull/734 is merged, then this PR is irrelevant and should be canceled. ensureInfraContainer is removed in that PR.
Adds a restart policy, so in case of a crash the container will restart. I'll implement this for the new API separately, please comment if you have any concerns about the restart policy as a general practice.

restart containers

---

infra/k8s/cluster.yaml

Choice of filename is because the AMI already has other configs in the `sysctl.d` directory:
```
root@ip-172-20-58-91:/etc/sysctl.d# ls -la
total 24
drwxr-xr-x  2 root root 4096 Apr  3 14:23 .
drwxr-xr-x 84 root root 4096 Apr  3 14:24 ..
-rw-r--r--  1 root root  468 Jan 17 11:42 01_ec2.conf
-rw-r--r--  1 root root 1519 Apr  3 14:23 99-k8s-general.conf
lrwxrwxrwx  1 root root   14 Jul 21  2019 99-sysctl.conf -> ../sysctl.conf
-rw-r--r--  1 root root  345 Apr  3 14:23 999-testground.conf
-rw-r--r--  1 root root  639 May 17  2018 README.sysctl
```

setting sysctl on the k8s hosts

---

infra/k8s/cluster.yaml
infra/k8s/install.sh

Kubernetes component of https://github.com/ipfs/testground/issues/781
This took me longer than I had hoped to figure out how to do this, and this is an undocumented kops feature, so I want to give an explanation.
All of the yaml stanzas are serialized into structs, the docker configuration struct is here: https://godoc.org/k8s.io/kops/pkg/apis/kops#DockerConfig
As you DefaultUlimit takes a slice/yaml-list of strings which are formatted with the same function as other docker ulimit strings. This is familiar.: https://github.com/docker/go-units/blob/master/ulimit.go#L66
Pretty simple!
To verify that this is working, log into one of the kops hosts, and have a look at any of the docker containers and see the result:
```
"Ulimits": [
{
"Name": "nofile",
"Hard": 1048576,
"Soft": 1048576
}
```

ulimits kubernetes using kops

---

infra/k8s/install.sh

Considering https://github.com/ipfs/testground/pull/768 we no longer need the `helm wait`.
We are confident that the default network is flannel, so no need to wait for resources to come up in order to continue with next steps.
Redis is required for some of the next DaemonSets, but they are implemented with `initContainers` that wait for it, so we are good there.

speed up install.sh

---

infra/k8s/cluster.yaml
infra/k8s/testground-infra/values.yaml

After a lot of investigation, let me explain what I've done here, parameter by parameter.
**`net.core.somaxconn = 131072`**
Bumped up to 128Ki -- for a good binary value. Note: this is the number of incoming sockets awaiting to be accepted, not the maximum number of connections we can maintain. It's a misnomer...
**`net.netfilter.nf_conntrack_max = 1048576`**
Let's use binary values.
**`net.ipv4.tcp_max_syn_backlog = 131072`**
This is the maximum number of incoming connections in SYN state. I don't think it needs to be so high. I was going to suggest 64Ki, but it doesn't hurt us to have a higher value, since our workloads are very bursty. So I rounded up to the next meaningful binary value.
**`net.core.netdev_max_backlog = 524288`**
This is the number of frames that can be outstanding …

update linux networking stack configuration.

---

infra/k8s/cluster.yaml

We need ECR access once we move the `testground daemon` to Kubernetes (so that it can build and push images).
Merging this earlier would be helpful when iterating on various features on Testground, so that I don't have to maintain multiple clusters (one with ECR access, one without (for `master`)), but rather iterate faster.

allow ecr access from k8s

---

infra/k8s/install.sh
infra/k8s/limit-range/limit-range.yaml
infra/k8s/testground-infra/values.yaml

Addresses https://github.com/ipfs/testground/issues/819
---
Ideally we don't want the OS OOM killer to kick in at any time, so we want to limit the resources on all containers with default.
These defaults can be overwritten by the pods themselves, but if a pod/container doesn't specify limits, it will use these.
TODO:

default container limits

---

infra/k8s/testground-infra/values.yaml

I think it is better if our `redis` pod has `QoS guaranteed`, rather than `QoS burstable`.
WDYT?
---
I haven't seen any manifestation in terms of performance, but under system load, these classifications would get into effect I guess.
https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

redis qos guaranteed - set both requests and limits

---

infra/k8s/testground-infra/values.yaml

Now that we have 2 nodes for testground infra, we need to be a bit more careful about where we schedule what - if `monitoring` pods (push-gateways, prometheus, grafana, operator, etc.) are spread between the 2 machines, we don't have enough space for Redis.
Therefore I am adding a few affinity and anti-affinity rules in order to make sure that Redis gets one host, and the monitoring pods get another host. The result is:
Redis host:
```
Non-terminated Pods:          (8 in total)
Namespace                   Name                                                         CPU Requests  CPU Limits   Memory Requests  Memory Limits  AGE
---------                   ----                                                         ------------  ----------   ---------------  -------------  ---
default …
```

move prometheus-operator to infra node. fix requests and affinity

---

pkg/runner/local_common.go

This PR applies proper configuration to Redis in local:exec and local:docker. Closes #727 for context.

local:{docker,exec}: proper config for redis container.

---

.gitignore
infra/k8s/efs-terraform/.gitignore
infra/k8s/install.sh

Routes before we install `sidecar`:
```
default via 172.20.32.1 dev eth0
100.96.0.0/24 via 100.96.0.0 dev flannel.1 onlink
100.96.1.0/24 via 100.96.1.0 dev flannel.1 onlink
100.96.2.0/24 via 100.96.2.0 dev flannel.1 onlink
100.96.3.0/24 via 100.96.3.0 dev flannel.1 onlink
100.96.4.0/24 via 100.96.4.0 dev flannel.1 onlink
100.96.6.0/24 via 100.96.6.0 dev flannel.1 onlink
100.96.7.0/24 via 100.96.7.0 dev flannel.1 onlink
100.96.8.0/24 via 100.96.8.0 dev flannel.1 onlink
100.96.9.0/24 via 100.96.9.0 dev flannel.1 onlink
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.20.32.0/19 dev eth0 proto kernel scope link src 172.20.55.130
```
---
Routes after we install sidecar (or at least the initContainer runs):
```
default via 172.20.32.1 dev eth0
100.64.0.0/16 via …
```

move weave and sidecar, prior to installing testground-infra

---

pkg/docker/manager.go

Docker filters docker container names by regex, but not labels.

docker: filter labels by value, not by regex

---

sdk/runtime/runner.go

1. Read may just read a single byte.
2. Make sure to actually close the body to avoid leaking.

fix: close response and read full

---

docs/USAGE.md
manifests/bitswap-tuning.toml
manifests/dht.toml
manifests/placebo.toml
pkg/api/definitions.go
pkg/api/runner.go
pkg/engine/engine.go
pkg/runner/cluster_k8s.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
plans/bitswap-tuning/main.go
plans/dht/main.go
plans/network/main.go
plans/placebo/main.go
sdk/runtime/output.go
sdk/runtime/runenv.go
sdk/runtime/runenv_test.go
sdk/runtime/runner.go
sdk/sync/redis_test.go

Fixes https://github.com/ipfs/testground/issues/466.
* Removes `TEST_CASE_SEQ` as an env variable, including its bindings in the `RunEnv`.
* Test plans now use `TEST_CASE` as a string selector for the test case to run.
* New `runtime.InvokeMap(map[string]runtime.TestCaseFn)` function for supplying a `string => func` map to select the test case from.

rm TEST_CASE_SEQ as a selector; replace with test case name.

---

infra/k8s/kops-weave/weave.yml
infra/k8s/testground-infra/values.yaml

I am decreasing resources for Redis, so that both Redis and Weave can fit on a c5.2xlarge.

increase weave resources ; decrease redis

---

infra/k8s/cluster.yaml

**Calculations:**
* Sizing for ~32768 connections per host. Hosts can run 100 containers. That's 3K conns per container + wiggle room for infrastructure (e.g. weave, prometheus, k8s, etc.)
* 32768 connections, 2 buffers each, 16KiB absolute minimum per buffer (first value of tcp_rmem and tcp_wmem) = 1GiB of global memory = 262144 pages (first pressure value of tcp_mem).
* max. buffer size = 4MiB, applicable separately to receive and send buffers.
---
TODO:

infra: expand network tcp buffers.

---

.travis.yml
Makefile
pkg/runner/local_docker.go

change ipfs/testground to iptestground/sidecar

---

.circleci/config.yml

Enabled docker layer caching on the linux build step. Lets see how much this improves the speed of CI.

docker layer caching

---

pkg/sidecar/k8s_network.go

Sidecar occasionally fails with:
```
Apr 24 09:32:14.513973  ERROR   sidecar worker failed: container worker failed: failed to add network through cni plugin: error setting up routes: failed to add route '{0.0.0.0 00000000} via 25.0.0.0 dev eth1': invalid argument     {"host": "unix:///var/run/docker.sock", "container": "87fab28e8ff20f6996c093f40a8e2acb61fd3f10b55114406408cee881e9bc36"}
```
I am not sure what `ip route add` is returning `invalid argument`.

add debugs for subnet and ip

---

pkg/build/golang/docker.go

Related with: https://github.com/testground/infra/pull/18
Addresses: https://github.com/testground/testground/issues/572
---
We need the `build container` to be on the `host` network, so that it can access a goproxy, which is also attached to the `host` network. Otherwise we have no way of discovering the goproxy service from our cluster (at least I couldn't figure out one).
---
TODO:

set build container network to `host` (needed for cluster:k8s runner)

---

pkg/sidecar/docker_reactor.go
pkg/sidecar/k8s_network.go
pkg/sidecar/k8s_reactor.go
pkg/sidecar/sidecar_linux.go

This will be needed for https://github.com/testground/testground/issues/907 and I can see this generalisation has been done for Docker already.
One change that I am introducing is that the sidecar doesn't panic if it can't resolve the IP of a service - allowing for both required and optional services.
---
This is useful for me, because I also run InfluxDB with almost every cluster, and want to have the route allowed, without having to recompile the sidecar.

generalise redis route to services routes; prepare for InfluxDB addition

---

pkg/runner/local_common.go

influxdb on common local healthchecks.
The authentication is disabled on this container.
Fix: https://github.com/testground/testground/issues/926

Add influxdb 1.8 to local healthchecks

---

pkg/runner/local_docker.go
pkg/runner/local_exec.go

SDK change implemented here: https://github.com/testground/sdk-go/pull/3/commits/429e8794f3f89424ca497afe4701b3b0a613ac28

rename INFLUXDB_ADDR env var to INFLUXDB_URL for correctness.

---

pkg/engine/engine.go

It looks like we are not accounting for the case where a specific `healthcheck` is failing, but we don't have a `fixer` for it - for example `redis` disappearing on our Kubernetes cluster.
In this case currently we respond to the user that `healthchecks: ok` which is misleading, so I suggest we at least give back a `warning` and continue with the run. (i.e. no change in behaviour)
After seeing the warning the user can call `testground healthcheck --runner cluster:k8s` and get a detailed report on what appears to be broken.

fix healthcheck feedback to user

---

env-example.toml

No need to confuse our users with defaults for `cluster:swarm` runner, that we no longer support.

amend example .env.toml

---

env-example.toml

I suggest we remove these from the sample `.env.toml`, because it is not normal for users to have to enter these at all.
Usually we pick up the default credentials from the host or the IAM policy.
I personally have never had to specify my credentials in this file, so I am not sure in what use-case one would want to do that.

remove aws credentials from sample .env.toml

---

pkg/runner/local_common.go

Fixes #954. It looks like macOS Catalina could be restricting some Docker RDB writes, if the persistence directory is not properly configured. Never seen this on macOS Mojave or Linux.
This PR fixes the `--save ""` option (it's possible that the escaping was not working well), and sets `stop-writes-on-bgsave-error` to `no`.
```
⟩ redis-cli
127.0.0.1:6379> config get *save*
1) "stop-writes-on-bgsave-error"
2) "no"
3) "rdb-save-incremental-fsync"
4) "yes"
5) "rdb-key-save-delay"
6) "0"
7) "save"
8) ""
127.0.0.1:6379> config get *stop*
1) "stop-writes-on-bgsave-error"
2) "no"
127.0.0.1:6379>
```

fix redis rdb snapshot complaints.

---

README.md

getting started is short! "how it works" is long. Suggest putting this first so it's easy for folks to scroll past, and then back to. This could also benefit from a few sentences added to the getting started to orient folks on WHAT they're trying to do and HOW to do it.

Put getting started above "how does it work"

---

plans/example/sync.go

I also updated the docs at https://docs.testground.ai/writing-test-plans/synchronization.
--
* no need to use a topic to get a seq; we can use a state.
* it's misleading to use the term "start" when that state actually ends the test.
* no need to set a deadline on the context; we can simplify.

example/sync: tidy up; remove superfluous pubsub.

---

pkg/cmd/plan.go

I've updated the quickstart docs accordingly:

plan create cmd: output location of new test plan.

---

plans/benchmarks/manifest.toml
plans/example/manifest.toml
plans/network/manifest.toml
plans/placebo/manifest.toml
plans/verify/manifest.toml

* `source_path`: needed no longer longer. Leftover from https://github.com/testground/testground/pull/849.
* builder configuration:
* `module_path` only needed if we're initialising a fresh gomod, which we aren't.
* `exec_path` not needed as go toolchain defaults to `.`
* overriding `go_version` not needed either

cleanup: remove cruft from sample manifest.toml files.

---

pkg/build/deps_go.go
pkg/build/deps_go_test.go
pkg/build/docker_go.go
pkg/build/exec_go.go
pkg/build/selector_test.go
pkg/engine/engine.go

Shuffle around a few things and flatten the `pkg/build` package to make it symmetric to `pkg/runner`.

flatten pkg/build package.

---

pkg/cmd/build.go
pkg/cmd/run.go

This PR is:
1. making the usage text for the `--link-sdk` option consistent
2. including the flags for `testground build composition` into `testground run composition`, essentially adding the `link-sdk` flag to `testground run`.
3. removing the common flags between `run compositon` and `build composition`, similar to how we do it for `testground run single` and `testground build single`.

add --link-sdk flag to run composition cmd

---

pkg/sidecar/k8s_network.go
pkg/sidecar/sidecar_linux.go

`default` is a special name of the only data network we currently set up and allow traffic shaping on.
Therefore it is best if we extract it and amend the docs at https://docs.testground.ai/traffic-shaping#configure-traffic-shaping to use `network.DefaultDataNetwork` and explain a bit better what this value is, together with `CallbackState`.

extract `default` network name

---

env-example.toml

We forgot to update the .env.toml when we added the extract functionality and renames for params.

fix .env.toml example

---

pkg/runner/cluster_k8s.go

I was under the impression that this is the default on Kubernetes, but it appears this is not the case, or something weird is going on with the image names.
1. Without this option, we are always pulling `busybox` (for the `mkdir-outputs` init container), resulting in a lot of latency when starting testplan pods.
2. If the tagged test plan image is on the machine, we don't pull it.
---
Note that even if our Docker build cache results in the same image, we are always allocating a unique `buildID` to the testplan images, resulting in Kubernetes pulling images on every testplan run, unless we use the `-w` option and specify exact `artifacts`. I think this is bad, and we have to rethink the tagging of our images.
For example:
Run 1:
```
Successfully built 64748d329558
Successfully tagged …
```

docker image: pull if not present

---

.circleci/config.yml
Makefile

`make test` doesn't work locally unless you have `placebo` and `example` in the `TESTGROUND_HOME` directory.
Therefore I am adding an `testground plan import` prior to the call to `go test` on every module.

fix make test

---

pkg/build/docker_generic.go
pkg/build/docker_go.go
pkg/build/registry.go
pkg/docker/image.go

Currently we are generating a unique build ID, and naming our test plan images with it, which results in unnecessary queries to the Docker Registry when Docker need to create containers from a given image.
This PR is updating the name scheme for our testplan images, so that we reference them with:
`<testplan-name>:<docker image id>`
---
We still need to keep the unique `BuildID` in order to determine the `docker image id` for a given Docker build (i.e. we call `docker image list` and filter based on the unique build id, in order to fetch the `docker image id`.

deterministic docker image name and tag

---

go.mod
go.sum
pkg/runner/cluster_k8s.go
pkg/runner/registry.go

This PR is adding in-memory LRU cache for pushed Docker images to remote repositories. I think it is worth having this, because it removes >10sec. per image from test plan runs that are trying to submit images that have already been pushed to a given remote.

LRU cache for pushed docker images

---

Makefile
integration_tests/06_docker_network_ping-pong.sh

This PR is adding a run for the `network/ping-pong` testplan, which exercises the `sidecar` and confirms we get two outputs with `outcome: ok` from the run.

integration tests for sidecar on local:docker

---

pkg/runner/local_docker.go
pkg/runner/local_exec.go

@coryschwartz not sure if `testground-goproxy` was emitted on purpose or not for `testground terminate`, but I think this command should be tearing down all containers and processes that Testground created. WDYT?

terminate go-proxy when testground terminate

---

go.mod
go.sum
pkg/runner/local_docker.go
pkg/runner/local_exec.go
pkg/sidecar/docker_reactor.go
pkg/sidecar/k8s_reactor.go

Addresses: https://github.com/testground/testground/issues/1006
---
This PR is adding an LRU cache to both K8s and Docker reactors to keep track of the `run-ids` that the `sidecar` has seen. The first time the `sidecar` sees a new `run-id`, it tries to resolve the necessary auxiliary services (influxdb, redis, etc.) so that we know which routes to allow when managing the networks for the test run containers.
---
TODO:
FOLLOW UP:

resolve services on each test run

---

Dockerfile.sidecar
Dockerfile.testground
Makefile
main.go
pkg/cmd/root.go
pkg/cmd/version.go
pkg/version/version.go

Addresses: https://github.com/testground/testground/issues/1041
---
Having a git commit is already a nice improvement and would make our lives easier when debugging other clusters (gossipsub, drand, etc.)
We should consider how we want to add a `semver` in the future.

add version command

---

pkg/sidecar/mock.go

Looks like with https://github.com/testground/testground/pull/939 we merged code that breaks compilation on MacOS, and we didn't catch this, since our CI only uses Linux.
This PR is fixing the build on MacOS, and I am also working on subsequent PR which will add a `job` on CircleCI, to confirm that unit tests (`go test`) and compilation works on MacOS.

sidecar: compile only on linux

---

.circleci/sidecar.yaml
Makefile
env-example.toml
env-kind.toml
integration_tests/header.sh
pkg/cmd/sidecar.go
pkg/runner/cluster_k8s.go
pkg/runner/local_docker.go

Addresses: https://github.com/testground/testground/issues/1055 and https://github.com/testground/testground/issues/1056
Also adds autoscaler support behind a feature flag.
Also adds configurable `collect` pod resource requests that were supposed to be addressed in #1008.
---
Ideally we don't want testplan pods to start on a given host before the dependencies have been started, and this is what this PR is about.
---
Related: Autoscaler PR on `testground/infra`: https://github.com/testground/infra/pull/43
---
TODO:

sidecar: start http server by default

---

.circleci/config.yml

This PR is adding a CircleCI build job for macOS.
At the moment we can't really run `go test` on CircleCI for macOS, because it relies on Docker.
TODO FOLLOWUP:

build job for macOS

---

integration_tests/01_k8s_kind_placebo_ok.sh
integration_tests/03_exec_go_placebo_ok.sh
integration_tests/04_docker_placebo_ok.sh
integration_tests/06_docker_network_ping-pong.sh
pkg/engine/engine.go
pkg/runner/common.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

This PR is:
1. Reverting `RunID` and `BuildID` to length 12, as there is a limit to image names and tags we can push to a Docker registry.
2. Updating the `collect outputs` functionality for `local:docker` and `local:exec` to return a gzip archive, and be consistent with `cluster:k8s`
4. Adding tests to make sure we stick to length 12 for RunIDs.
@coryschwartz is there a reason for the change in the UUID for the build and the run IDs?
---
Fixes https://github.com/testground/testground/issues/1065
Fixes https://github.com/testground/testground/issues/1068

change zip to gzip for all runners ; revert run/build ids to length 12

---

pkg/cmd/run.go

Fixes https://github.com/testground/testground/issues/1070.
Unfortunately urfave CLI does not allow you to omit the default value indication, so we have to resort to this hack.

cli: fix misleading default value.

---

pkg/build/docker_go.go
plans/dockercustomize/manifest.toml

For builds that do more than just compiling go code (e.g. generating things, linking to dynamic libs, etc.), we might want to just use the build container as our runtime container. This is suboptimal, but it's a good way to bootstrap a test plan for a complex target, like Lotus/Filecoin.

docker:go: add option to skip runtime image.

---

pkg/api/engine.go
pkg/api/rpc.go
pkg/build/docker_generic.go
pkg/build/docker_go.go
pkg/cmd/terminate.go
pkg/daemon/terminate.go
pkg/docker/container.go
pkg/docker/docker_test.go
pkg/docker/image.go
pkg/docker/output.go
pkg/engine/engine.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
pkg/runner/registry.go
plans/dockercustomize/manifest.toml

This commit introduces rolling/carry-over go build caches as a default behaviour in docker:go. Build caches images are maintained per test plan + go version tuple. Every time a build is started, we check if we have an image from a previous build, and if so, reuse it (clearing /plan, /sdk, /testground_dep_list first).
If a prior build cache image doesn't exist, we start with a blank go container.
The goal is to carry over the entire /go directory, which contains the pkg cache. We also set GOCACHE to /go/cache, in order to carry over the build object cache.
This behaviour can be disabled by setting the `disable_go_build_cache=true` option in the builder configuration.
The tradeoffs are as follows of using the rolling cache are as follows:
* good: the rolling cache leads to super-fast go …

docker:go: rolling go build caches; make builders `Terminatable`; add basic termination logic to `docker:go`

---

pkg/api/builder.go
pkg/api/engine.go
pkg/api/manifest.go
pkg/build/docker_generic.go
pkg/build/docker_go.go
pkg/build/exec_go.go
pkg/build/selector_test.go
pkg/client/client.go
pkg/cmd/build.go
pkg/daemon/build.go
pkg/engine/engine.go

This allows us to create isomorphism in complex builds, such as when test plans depend on external artifacts.
It also allows us to ship assets external to the test plan source.
Additionally, it unlocks the ability to override dependencies (e.g. via replace directives) replacing them with local copies. With the go builders, users no longer need to push changes in their upstream repos to get them picked up in their test plans.
1. Manifests can now specify an `extra_sources` map, consisting of `builder => []paths`, which specify which paths to include as extras for which builders (conditional activation).
2. The paths are resolved relative to the plan source directory (where the manifest resides), evaluating symlinks first. This makes use that if the plan under `$TESTGROUND_HOME/plans/planA` …

add the ability to ship extra local sources in builds.

---

go.mod
go.sum
pkg/api/composition.go
pkg/api/composition_test.go
pkg/build/selector_test.go
pkg/cmd/build.go
pkg/cmd/common.go
pkg/cmd/run.go

Compositions can now specify `[build]` and `[run]` subtables in the `[global]` table.
Build and run settings in groups will inherit the default configuration. The coalescing will happen in this manner:
* `build.dependencies` => the default dependency set will be merged into the local one, with the local entries taking precedence.
* `build.selectors` => no merging; the local selector list will override the default selector list entirely.
* `run.artifact` => local artifacts take precedence over default.
* (known issue: if a global artifact is set, there's no way to "unset" it for a group, so that a build is triggered.)
* `run.test_params` => the default test parameters will be merged into the local map, with the local entries taking precedence.
---
Fixes #521.
Closes #648 (fix included …

compositions: trickle default configs to all groups.

---

pkg/runner/cluster_k8s.go
pkg/runner/common_ports.go
pkg/runner/local_docker.go

This facilitates isomorphism across runners, because test workloads can now rely on port numbers being set via environment variables, instead of hard-coded values in source.
- port numbers are now specified as a map `label => port`, _à la Docker compose_.
- `local:docker` and `cluster:k8s` support port mappings and thus inject the port numbers as env variables with the name `${LABEL}_PORT`.
- `local:exec` will not inject anything because it doesn't support this feature (TODO/UX: print a warning in the runner informing that port mappings are not applied?).
- https://github.com/testground/sdk-go/pull/24 allows us to load such port numbers, and specify fallbacks if they're not set (e.g. `0` -- random).
---
Fixes https://github.com/testground/testground/issues/1094.

inject port numbers as env variables.

---

pkg/cmd/run.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

* In `local:exec`, we now identify instances in the pretty log output with: `<< group_id[idx] >>`
* In `local:docker`, we use the tag: `<< group_id[idx] (container_id[:6])`.
Since it's not obvious that composition-less runs via CLI are mapped to a singleton group named `single`, I've added a log statement for UX purposes.
This is what it looks like on `local:exec`:
---
Fixes https://github.com/filecoin-project/oni/issues/152.
---
cc @schomatis.

informative instance tags in pretty log printer.

---

pkg/api/builder.go
pkg/api/composition.go
pkg/api/composition_test.go
pkg/build/docker_go.go
pkg/cmd/common.go
pkg/engine/engine.go

This PR should close #48 by allowing cross-repository replacement directives for dependencies on the `docker:go` builder. I followed @raulk instructions on [this comment](https://github.com/testground/testground/issues/48#issuecomment-536328534). Some thoughts:
> 1. Adopt go.mod notation in the CLI `--dep` parameter: `<dependency>=[<target>]@<version>`. When `target` is missing, we assume no remapping of repos.
Done.
The current iteration is forcing the `@` to be present just like the specification. Should it be optional when we only have a version?
>2. Adjust the components mentioned above. The `build.Input.Dependencies` field turn into a `map[string]DependencyTarget`, where `DependencyTarget` is a struct containing the target and version.
Done.
>3. In the future, to preserve …

feat: `docker:go` cross-repo dependency replacement

---

plans/dockercustomize/manifest.toml

- Related to https://github.com/testground/testground/pull/1081

docs: add `build_base_image` to dockercustomize manifest

---

integration_tests/01_k8s_kind_placebo_ok.sh
integration_tests/02_k8s_kind_placebo_stall.sh
integration_tests/03_exec_go_placebo_ok.sh
integration_tests/04_docker_placebo_ok.sh
integration_tests/05_docker_placebo_stall.sh
integration_tests/06_docker_network_ping-pong.sh
pkg/cmd/itest/build_test.go
pkg/cmd/itest/common_test.go
pkg/cmd/itest/describe_test.go
pkg/cmd/itest/list_test.go
pkg/cmd/itest/run_test.go
pkg/cmd/itest/sidecar_test.go
pkg/healthcheck/checkers.go
pkg/healthcheck/fixers.go
pkg/runner/local_exec.go

This closes #959 by adding a healthcheck rule to `local:exec` that fails if the default redis port is unavailable, aborting the healthchecker.
I wasn't sure if we should abort or just fail because just failing the healthchecker would give the user a warning and not much information. This way it is clearer that local redis instances need to be  stopped.
License: MIT

feat: detect redis port collision on local:exec

---

pkg/api/builder.go
pkg/api/engine.go
pkg/api/rpc.go
pkg/build/docker_generic.go
pkg/build/docker_go.go
pkg/build/exec_go.go
pkg/client/client.go
pkg/cmd/build.go
pkg/daemon/build.go
pkg/daemon/daemon.go
pkg/engine/engine.go

This PR closes #1088 by removing the rolling cache mechanism and replacing it by a more manual cache process. Now, the cached image is only built once and the developer decides when to reset/clear the cached image.
To enable the cache, the option `enable_go_build_cache` must be set to true, just like it is done right now. When it's true, two things can happen:
1. If there's no cached image, we cache the intermediate later right before the runtime phase.
2. If there's a cached image, use it as a base.
To clear up the cache, you can run:
```
testground build purge --builder docker:go --plan <test-plan-name>
```

docker:go: replace rolling cache by static cache

---

env-example.toml
env-kind.toml
pkg/client/client.go
pkg/cmd/itest/common_test.go

This PR is updating the endpoint format in `.env.toml` so that we can specify `https` endpoints, and have a Testground daemon exposed on the internet (with https://github.com/testground/infra/pull/58)

allow https endpoints for daemon

---

pkg/sidecar/docker_network.go
pkg/sidecar/docker_reactor.go
pkg/sidecar/k8s_network.go
pkg/sidecar/k8s_reactor.go
pkg/sidecar/route.go

Closes #1116. To implement the AllowAll and BlockAll traffic policies on k8s, I followed a similar approach to what was done in #1107: saved the external routes on the data plan, which uses Weave plugin, and we now remove the default route when we want to block external traffic, or add it when we want to allow it.
I run a few tests to make sure this doesn't break container-to-container communication in other tests. I hope it makes sense. They all passed!
<details>
<summary>
network/traffic-allowed
</summary>
```
$ testground run single --builder docker:go \
--runner cluster:k8s \
-i 1 --plan network --testcase traffic-allowed \
--collect
```
**Output:**
```
{"ts":1596635995586585358,"msg":"","group_id":"single","run_id":"0fb1e476d206","event":{"type":"message","message":"registering …
```

cluster:k8s: implement traffic policies

---

pkg/cmd/describe.go

The `describe` command uses flags and not arguments. Let's fix that help text!
License: MIT

fix: 'testground describe' does not have args

---

pkg/runner/local_exec.go

PATH was not being injected and led to error over Linux:
```
Aug 13 09:20:04.939750  INFO    0.0707s       FAIL << instance   2 >> exec: "getent": executable file not found in $PATH       {"req_id": "0ad73835"}
```

fix: local_exec path injection 

---

pkg/build/docker_go.go

This PR is adding a flag to control cgo.
Note that it is also changing the default behaviour in Testground when using the `docker:go` builder, as by default now Cgo will be disabled. See https://github.com/testground/testground/commit/950238a9f41ed184eddeabf9876bb5a681beee0a#r41587533
---
cc @adlrocha 
---
Fixes #1131 #1130.

add flag to control cgo

---

pkg/engine/engine.go

Fixes tasks ordering: scheduled, then processing, then completed. The newest is on top. Partially addresses #1146.

fix: tasks ordering

---

pkg/api/engine.go
pkg/api/rpc.go
pkg/client/client.go
pkg/cmd/build.go
pkg/cmd/logs.go
pkg/cmd/run.go
pkg/cmd/tasks.go
pkg/config/env.go
pkg/daemon/daemon.go
pkg/daemon/logs.go
pkg/daemon/outputs.go
pkg/daemon/run.go
pkg/daemon/tasks.go
pkg/engine/engine.go
pkg/engine/supervisor.go
pkg/logging/log.go
pkg/task/task.go

This PR is:
1. Adding `SlackWebhookURL` to which we publish a message when a task is completed. We don't do anything if this field is empty.
2. Adds 3 GET endpoints:
```
/tasks - lists all tasks
/logs - used to fetch logs for a given task
/outputs - returns a download of the outputs tgz for a given task
```
TODO:

initial notification to slack on completed task ; basic html pages for tasks and logs

---

pkg/build/exec_go.go

This enables step-through debugging when attaching a debugger.
Otherwise, breakpoints and step-through won't line up with source.
Recommended by https://blog.jetbrains.com/go/2019/02/debugging-with-goland-getting-started/
---
Obviously this has an impact on test plan performance, and therefore any metrics that are captured. We might want to turn it into a flag, but it's also worth noting that `local:exec` is meant for quick iteration and debugging, rather than actual reproducible runs (as there is no isolation).

exec:go: build with no optimisations nor inlining.

---

go.mod
pkg/sidecar/k8s_reactor.go

This PR is explicitly adding a route to the gateway, because otherwise packets to DNS (and other services) are dropped:
```
/ # ip route
28.116.0.0/16 dev eth1 scope link  src 28.116.128.0 # data network
30.0.0.0 dev eth1 scope link # data network
blackhole 100.64.0.0/10 # we want to drop packets to the services CIDR apart from DNS
100.64.0.10 via 100.96.4.1 dev eth0 # this is DNS
100.96.1.9 via 100.96.4.1 dev eth0 # this is influxdb
100.96.3.3 via 100.96.4.1 dev eth0 # this is redis
blackhole 100.96.4.0/24 # we want to drop packets to all destinations at 100.96.4.x except 100.96.4.1
100.96.4.1 dev eth0 scope link # the route we are adding in this PR
```
---
This problem got triggered when upgrading Kubernetes, weave and flannel, as well as host OS from `debian 9 stretch` to `ubuntu` …

add route to gateway, so that we dont blackhole it

---

pkg/build/exec_go.go

* There was a minor bug when trying to replace dependencies with `exec:go`.

Fixed exec:go replace

---

pkg/cmd/run.go

Fixes #1197
I chose to go for the built-in Go templates to avoid more dependencies and they're more flexible in the long run.

feat: support env vars in composition files

---

plans/benchmarks/manifest.toml

This PR is removing the `all` test case from the manifest.toml of the sample `benchmarks` test plan, as there is no such test case, and this is confusing.
cc @shapnam83

testplan benchmarks: remove `all` testcase

---

go.mod
go.sum
pkg/api/composition.go
pkg/api/runner.go
pkg/cmd/tasks.go
pkg/engine/supervisor.go
pkg/runner/cluster_k8s.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go
pkg/sidecar/docker_links.go

This PR introduces the ability to tell test plans to capture system profiles automatically.
For support on the Go SDK, check out this PR: https://github.com/testground/sdk-go/pull/38
There is now a new `profiles` field in `run` parameters, that can be set globally, or per-group:
```toml
[global]
plan = "libp2p/ping"
case = "ping"
total_instances = 10
builder = "docker:go"
runner = "local:docker"
[global.run]
profiles = { cpu = "", heap = "5s", allocs = "10s" }
```
It takes a map of string => string, where the key is the profile type, and the value is the frequency (in Go `time.Duration` string representation, e.g. `5s`, `1m`).
For Go test plans:
* `cpu` => starts a CPU profile for the entire duration of the test job; the value is ignored.
* any other type listed in the godocs for the …

add support for capturing profiles.

---

go.mod
go.sum
pkg/runner/local_docker.go
pkg/runner/local_exec.go

A temporary directory is created per instance on the host's file system.
It is then injected into the test instance via the `TEST_TEMP_PATH` directory.
After the run finishes, the runner cleans up all temporary directories.
Use this to generate large random files, instantiate databases, etc.
Go SDK support: https://github.com/testground/sdk-go/pull/39
---
TODO for a future PR:
- Support in `cluster:k8s` runner.

add support for temp directories to local:exec and local:docker runners.

---

.circleci/config.yml
Dockerfile.sidecar
Dockerfile.testground
README.md
go.mod
go.sum
pkg/build/docker_go.go
plans/benchmarks/go.mod
plans/benchmarks/go.sum
plans/dockercustomize/go.mod
plans/dockercustomize/go.sum
plans/dockercustomize/manifest.toml
plans/example/go.mod
plans/example/go.sum
plans/network/go.mod
plans/network/go.sum
plans/placebo/go.mod
plans/placebo/go.sum
plans/splitbrain/go.mod
plans/splitbrain/go.sum
plans/verify/go.mod
plans/verify/go.sum

The newer versions of Go have support for far more functionality so I'm updating the defaults of build images to Go 1.16.

chore: upgrade to Go 1.16 and change defaults

---

go.mod
go.sum
pkg/api/composition.go
pkg/api/runner.go
pkg/engine/supervisor.go
pkg/runner/cluster_k8s.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

Fixes #1232.
Depends on https://github.com/testground/sdk-go/pull/41.
Composition example:
```toml
[metadata]
name    = "test"
author  = "test"
[global]
plan    = "network"
case    = "ping-pong"
builder = "docker:go"
runner  = "local:docker"
emit_dumps = 5
total_instances = 2
[global.build_config]
go_version = "1.16"
[[groups]]
id = "all"
instances = { count = 2 }
```
Emits goroutine dumps every 5 seconds on each test instance. Plan `network` needs to be upgraded to SDK in linked PR in order for this to work.

feat: emit periodic goroutine dumps

---

.circleci/config.yml

Homebrew got updated on Circle CI and the new version does a shallow git clone by default so `brew update` fails. I simply removed that step as the newest version of Go should be available without needing to update brew.
License: MIT

fix: macOS CI

---

pkg/task/storage.go
pkg/task/storage_test.go

Fix panic "task key must be a xid id" by returning error instead.
Fixes #1241.
License: MIT

fix: return error instead of panicking

---

go.mod
go.sum
pkg/api/composition.go
pkg/api/runner.go
pkg/engine/supervisor.go
pkg/runner/cluster_k8s.go
pkg/runner/cluster_swarm.go
pkg/runner/local_docker.go
pkg/runner/local_exec.go

Reverts testground/testground#1234.
The feature is already covered by https://github.com/testground/sdk-go/pull/38 and https://github.com/testground/testground/pull/1209 by using the "goroutines" profile.

Revert "feat: emit periodic goroutine dumps"

---

integration_tests/01_k8s_kind_placebo_ok.sh

Enables Redis using the docker healthcheck on the first k8s integration test. Something similar is already being done on the second test. However, the first one was silently failing to connect to Redis.

fix: enable Redis on k8s test

---

pkg/cmd/build.go
pkg/cmd/run.go
pkg/daemon/build.go

extra_sources wasn't working for me and when I dug deeper I found out there was a missing conversion. The builder had to be changed from `docker:generic` to `docker_generic` .

fix: extra_sources builder reference

---

pkg/runner/local_common.go

Fixes #1230.
**After merge:** add to docs the necessity to change this sysctl on the host system (eg [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docker.html#docker-cli-run-prod-mode)).
License: MIT

fix: do not change read-only non-namespaced sysctl

---

pkg/client/client.go

This adds some logic to the client to handle HTTP errors. We return an error in case the status code is >= 400 or if the content type is not JSON.
This fixes #1198 as the problem is not Testground by itself, but the lack of presenting the actual error.
License: MIT

fix: handle http error on client

---

.circleci/config.yml

Updating xcode as the current version is being deprecated on Circle CI: https://github.com/circleci/circleci-docs/pull/6054

chore: update to xcode 13.2.0

---

plans/example-js/failure.js
plans/example-js/output.js
plans/example-js/package-lock.json
plans/example-js/package.json
plans/example-js/pingpong.js
plans/example-js/sync.js

Fixes #1303 
The javascript examples always end in "failure" because we never emit the success signal to the sync service.
This PR adds a `client` parameter inside javascript tests, which triggers the initialization of the sync client.
It's similar to the `InitializedTestCaseFn` used in go examples,
See https://github.com/testground/sdk-js/pull/22

plans/example-js: fix test using new default client

---

.circleci/sync-service.yaml
Makefile
pkg/runner/cluster_k8s.go
plans/placebo/main.go

We're patching `testground run --wait` to make the CLI exit code consistent with the testground outcome in https://github.com/testground/testground/pull/1347. We want to make sure that if the test outcome is a failure, the command fails.
But now, integrations tests in #1347 fail because the `placebo` test outcome is `failure` (see comments in #1304 for more details) and the CLI catches this outcome (which is the new, expected, behavior).

fix: update test & ci to use the sync service

---

Makefile
integration_tests/15_02_docker_mixed_builders_and_custom_go_deps.sh
pkg/build/docker_go.go
plans/_integrations_mixed_builders/_compositions/issue-1412-path-and-go-dependencies.toml
plans/_integrations_mixed_builders/go/main.go
plans/_integrations_mixed_builders/manifest.toml

fix: in docker:go builder, path & modfile options can't be mixed

---

pkg/runner/cluster_k8s.go
pkg/runner/common.go
pkg/runner/common_result.go
pkg/runner/local_docker.go

Fix #1400
Fix #1382
When the docker runner starts a test run it does a few things:
1. Wait for the instance containers to complete,
2. Setup a "pretty printer" that forwards instance's stdout, BUT ALSO tries to decode events from stdout and update the outcomes, 
3. Listen to the events sent by test instances and update the outcomes on success.
When the containers exits (1) testground stops everything related to collecting the outcomes (3).
This is fine-ish with the go-sdk because it dumps events to stdout as well, so the outcomes will be read thanks to (2).
Logging events on stdout and trying to decode the JSON looked like a legacy hack: this was not implemented in the rust-sdk. See my [notes on the pretty printer](https://github.com/testground/testground/issues/1322#issuecomment-114120932 …

fix: testground instability due to race condition on outcomes

---

go.mod
go.sum
pkg/api/composition.go
pkg/api/composition_test.go
pkg/build/docker_generic.go
pkg/build/docker_go.go
pkg/cmd/build.go
pkg/cmd/fixtures/templates/missing-ressource.toml
pkg/cmd/fixtures/templates/resource-complex.toml
pkg/cmd/fixtures/templates/resource.toml
pkg/cmd/fixtures/templates/with-resource-complex.toml
pkg/cmd/fixtures/templates/with-resource-complex.toml.expected
pkg/cmd/fixtures/templates/with-resource.toml
pkg/cmd/fixtures/templates/with-resource.toml.expected
pkg/cmd/run.go
pkg/cmd/template.go
pkg/cmd/template_test.go
pkg/engine/supervisor.go

- This lets a user define configuration in a file (like a list of instances) and use them during composition templating.
- When working on rust interop tests, I noticed we lose the benefits of docker caching & explodes storage requirements because we start every build at the same time.

feat: various usability & stabiliy improvements for interop

---

pkg/cmd/build.go

At the moment the composition output is not closed or truncated.
Which means the following case may happen:
input:
```
Line 1
Line 2
Line 3
```
expected output:
```
Line A
Line B
```
actual output:
```
Line A
Line B
Line 3
```

cmd/build: fix `write-artifacts` to correctly truncate & close the output

---

env-kind.toml
integration_tests/19_limit_runs_per_branch.sh

Fix the test introduced in https://github.com/testground/testground/pull/1399 and enabled in https://github.com/testground/testground/pull/1467.
With > 1 runner, both tasks are scheduled at the same time, which means that they are never cancelled (we don't cancel running tasks yet).

integration_test: fix interop test 19

---

integration_tests/13_02_docker_builder_configuration.sh
integration_tests/13_docker_builder_configuration.sh
integration_tests/15_docker_mixed_builders_configuration.sh
integration_tests/header.sh

The `if` condition is always true. With the change, the `if` condition is true only when `SKIP_LOG_PARSING` is set to a non-empty string.
``` bash
> echo $SKIP_LOG_PARSING
>
> if [ SKIP_LOG_PARSING ]; then echo "skip"; fi
> skip
> if [[ -n "$SKIP_LOG_PARSING" ]]; then echo "skip"; fi
> SKIP_LOG_PARSING=true
> if [[ -n "$SKIP_LOG_PARSING" ]]; then echo "skip"; fi
> skip
```

Fix SKIP_LOG_PARSING condition

---

pkg/runner/local_common.go

In InfluxDB v1.8, Flux is [disabled by default](https://docs.influxdata.com/influxdb/v1.8/flux/installation/). This PR enables [Flux](https://docs.influxdata.com/influxdb/v1.8/flux/) for `local` runner so we can use the useful features like `histogram()`.

InfluxDB: enable Flux

---

CHANGELOG.md
Makefile
integration_tests/20_exec_go_mod_rewrites.sh
pkg/build/exec_go.go
plans/placebo/_compositions/pr-1469-override-dependencies.toml
plans/placebo/go.mod

I was trying to run a composition that used different dependencies for the different instances using `exec:go`. I was setting the instances' dependencies in the `composition.toml` as follows: 
```toml
[[groups]]
id = "attacker"
[groups.build]
[[groups.build.dependencies]]
module = "github.com/filecoin-project/lotus"
version = "8f48631fc48773821fd853b6d9612380b9d74cb4"
```
When running the composition I kept getting the error: `task cancelled due to error     {"err": "task of type run cancelled: unable to add replace directives to go.mod; exit status 1; output: "}`.
Inspecting the code, I realized that the `dependency.Target` had to be set explicitly for it to work with `exec:go`. Modifying the dependency for the instance in the `composition.toml` to the following made it work.
```toml …
```

fix: go dependencies rewrite in exec:go

---

plans/example-rust/src/main.rs

- use tokio's TcpListener and TcpStream to not block the executor thread.
- remove remaining unwraps.
- cargo fmt

example-rust: improve test-case:

---

ROADMAP.md

It’s unlikely we’ll bring in an EKS engineer this year, which means we have to refine our focus and prioritize other critical work. This Roadmap takes these changes into account and comes up with a different plan that:

feat: update roadmap 2023

---

.github/workflows/pr-update-on-author-input.yml

Contributes to https://github.com/testground/testground/issues/1511

ci: remove hint/needs-author-input when the author comments

---

CHANGELOG.md
go.mod
go.sum
install.sh
integration_tests/19_limit_runs_per_branch.sh
pkg/config/loader.go

Having TESTGROUND_HOME directory in `~/testground` pollutes my $HOME. There are standards for application data/cache/config across operating systems, see https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and https://github.com/adrg/xdg
For linux/unix:
`~/.config/testground`
For Mac/Darwin:
`~/Library/Application Support/testground`

feat: Use XDG Base Directory Specificationfor TESTGROUND_HOME directory

---

.github/workflows/integration-tests.yml
pkg/integration/local_docker_test.go
pkg/integration/utils/daemon.go
pkg/integration/utils/entrypoints.go
pkg/integration/utils/requires.go
pkg/integration/utils/types.go
pkg/runner/local_docker.go
plans/_integrations/main.go
plans/_integrations/manifest.toml

Relates to #1542
Closes https://github.com/testground/testground/issues/1551
When a job reaches the timeout, it's not very clear that it was canceled.

local_docker: make it more explicit when a test is killed when reaching a timeout

---

ROADMAP.md

Notes on why imho 3 points should be included in the vision section: 
Currently, our documentation is very `todo-list`ish and users(me included back in time) faced harshed realities of implementation for their projects' needs. Async hand-holding is needed as I've heard multiple times that nailing down the concept of testground is not straight-forward and is causing issues like: 
- https://github.com/testground/testground/issues/1336 - compositions are hard to nail down. Especially when a user opens the `runenv` APIs and discovers that there are multiple ways to treat the test-run instance's perspective
- https://github.com/testground/testground/issues/1378 - classic Dunning-Kruger effect that should be populated somewhere in docs that blocking calls should be treated with extra-caution …

doc: add documentation and rollups example to roadmap's vision
