testground/testground

- pkg/runner/local_docker.go
Fixes a bug where the `local:docker` runner didn't start the newly-created Redis container.
> `local:docker` runner: start redis container.

- README.md
- cmd/run.go
Note, this PR is still a draft. I opened so that I can I ask questions/make comments as I go
> Documentation on how to use TestGround

- pkg/build/docker_go.go
- pkg/runner/local_docker.go
- pkg/util/docker.go
Fixes an issue reported in #59.
> runner/local:docker: pull redis image.

- _meeting-notes/06-08~01-10-2019.md
As part of my rehaul to where the information about the project lives. I'm importing the previous notes here.
> Import previous notes

- README.md
@daviddias I've added some questions in here, if you can look!
> More clarifications about running locally

- docs/tests-mvp.md
As I learn how to implement Test Plans and look back at the spec, Iearn of new elements that need to exist. This PR separates the Test Plan Parameters from the Test Case Parameters
> differentiate plan parameters from test parameters

- plans/chew-large-datasets/README.md
Applying https://github.com/ipfs/testground/issues/80
> docs(plan): apply Steven's review from #80

- plans/naming/README.md
I've merged them all into the same test as the _test_ is the same for each router (and we usually use multiple routers in parallel).
> flesh out a naming test plan

- manifests/dht.toml
- pkg/runner/local_docker.go
- plans/dht/test/lookup_peers.go
- sdk/runtime/output.go
- sdk/sync/subscription.go
> fixes on sync service, DHT find_peers test case, and elsewhere

- README.md
- pkg/engine/dirs.go
* We now check the executable directory and the working directory.
* Improved README.
Addresses #127.
> Harden the logic to guess the testground's source dir

- pkg/build/golang/docker.go
- pkg/runner/cluster_swarm.go
- pkg/util/options.go
- plans/dht/go.mod
See commit log. Merge with merge, not squash.
> Various minor fixes

- pkg/engine/dirs.go
Explaination in the code itself!
> fix: find SRCDIR on windows

- cmd/all.go
- cmd/describe.go
- go.mod
- go.sum
- manifests/dht.toml
- pkg/api/definitions.go
Fixes #45.
Test with: 
- `testground describe dht`
- `testground describe dht/find-peers`
> add a describe command.

- pkg/build/golang/docker.go
- pkg/docker/network.go
- pkg/runner/local_docker.go
We need network access to build.
> fix(build/docker): don't use an isolated network

- cmd/all.go
- cmd/build.go
- cmd/describe.go
- cmd/list.go
- cmd/run.go
> fix(cmd): run without source

- docs/SPEC.md
- docs/USAGE.md
Just looking around and found some dead links.
> docs: fix dead links

- docs/ROADMAP.md
As requested by the IPFS Project Lead, @momack2 :) 🚀 💎 
The Roadmap as it stands is kind of redundant to the OKRs for Q4. It might prove to become a good instrument for planning for multiple quarters at a time when 2020 plans are made.
@raulk I would love your review first as the Tech Lead / Architect for the project, so that then others can review.
> Create a Roadmap for TestGround

- pkg/sidecar/link.go
Bandwidth -> htb
Latency -> netem
> fix(sidecar): consistent naming of queue handles

- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/EPIC.md
- .github/ISSUE_TEMPLATE/FEATURE.md
fixes https://github.com/ipfs/testground/issues/205
> Issue templates

- plans/chew-large-datasets/main.go
- sdk/iptb/daemon.go
Simplifies the daemon creation from the POV of the test plan.
License: MIT
> feat: spawn daemon IPTB

- cmd/run.go
- pkg/api/runner.go
- pkg/daemon/client/client.go
- pkg/daemon/client/types.go
- pkg/engine/engine.go
- pkg/server/run.go
personally, I don't like the strategy of just checking for the compatibility on the running phase. However, it was the simplest change I could do to make it work.
Closes #191.
License: MIT
> feat: check for runner/builder compatibility

- manifests/dataexchange.toml
- plans/data-transfer-seeds-leeches/Dockerfile
- plans/data-transfer-seeds-leeches/README.md
- plans/data-transfer-seeds-leeches/go.mod
- plans/data-transfer-seeds-leeches/main.go
- plans/data-transfer-seeds-leeches/test/transfer.go
- plans/data-transfer-seeds-leeches/utils/createnode.go
- plans/data-transfer-seeds-leeches/utils/files.go
- plans/data-transfer-seeds-leeches/utils/metrics.go
- plans/data-transfer-seeds-leeches/utils/peers.go
- plans/data-transfer-seeds-leeches/utils/state.go
- plans/data-transfer-seeds-leeches/utils/walker.go
Fixes https://github.com/ipfs/testground/issues/79
> WIP: Create Test Plan Spec : Data transfer: seeds / leeches (Bitswap Specifics)

- .travis.yml
- README.md
> feat: run codecov in CI

- docs/ROADMAP.md
> Spelling fixes

- plans/bitswap-tuning/.gitignore
- plans/bitswap-tuning/go.mod
- plans/bitswap-tuning/main.go
- plans/bitswap-tuning/test/transfer.go
I'm assuming the binary wasn't supposed to be there.
> Delete checked in binary, fix test renaming inside go.mod and *.go files

- pkg/runner/console.go
- pkg/runner/local_docker.go
- pkg/runner/local_exec.go
* Pretty print
* Return a non-zero exit code on failure (fixes CI).
* Fix the find peers test
> Improve test output. No more false positives on CI

- plans/smlbench/main.go
On a PR yesterday, this slipped under our fingers and main.go got removed from smlbench test!
License: MIT
> revert: smlbench

- manifests/dht.toml
> feat: add defaults to dht manifest

- cmd/run_test.go
> test: test aborted test should fail on docker

- sdk/sync/redis_test.go
- sdk/sync/subscription.go
Relates to #252. This PR introduces two tests to cover:
* subscription before first write (i.e. while the key still doesn't exist): ensures that the subscriber "latches onto" the subtree and that all writes are consequently received.
* write before subscribe: writes all keys, then subscribes. Checks that the sync service correctly replays the state to the subscriber.
These tests are writing 1000 keys, and they're passing iteration after iteration, so something else is at play here, and I think I have an idea -- could be a very specific race between the moment between we subscribe and we acquire the last seq. But that would only make sense if we miss very few items.
> sdk/sync: improve test coverage.

- infra/k8s/README.md
- infra/k8s/redis-values.yaml
- infra/k8s/sidecar.yaml
This is the initial tutorial on using Testground with Kubernetes on Digital Ocean.
Ideally it should be as brief as possible and not verbose, while at the same time providing all the details a developer needs.
I want to avoid having to document knowledge that 99% of the company has, or knowledge that can easily be found with a single Google Search, while staying on point.
Any feedback is very welcome ;)
> initial tutorial on using Testground with k8s/DO

- infra/docker-swarm/README.md
- infra/docker-swarm/ansible/roles/swarm-init/tasks/main.yml
- infra/docker-swarm/ansible/roles/swarm-join/tasks/main.yml
This PR is removing a few commented out lines, and also testing the automated Docker Cloud build on push to `master` - we should get an automated build generating an image on `ipfs/testground:edge`.
> remove commented out lines

- plans/chew-datasets/main.go
> fix: new datasets uses new params api

- plans/bitswap-tuning/test/transfer.go
- plans/bitswap-tuning/utils/createnode.go
Update plans to reflect changes in the SDK API
> Fix bitswap plans

- docs/USAGE.md
- infra/k8s/README.md
- pkg/build/golang/docker.go
- pkg/build/golang/exec.go
- plans/bitswap-tuning/test/transfer.go
> fix: remove the cache

- plans/bitswap-tuning/test/transfer.go
- plans/bitswap-tuning/utils/net.go
- plans/dht/test/common.go
Addresses some comments on https://github.com/ipfs/testground/pull/352
> Address review comments on Bitswap plan PR

- infra/k8s/README.md
dummy.yml instead of dummy.yaml
> k8s - fix file extension in docs

- infra/k8s/kops-weave/weave.yml
- pkg/runner/cluster_k8s.go
partial fix for https://github.com/ipfs/testground/issues/392
> improve IP address assignment on k8s

- pkg/runner/eventmanager.go
The existing code was reusing a variable which confuses the json decoder
> Fix bug with decoding json logs

- pkg/runner/cluster_k8s.go
> fix: set log level in cluster k8s

- infra/k8s/README.md
- infra/k8s/kops-weave/weave.yml
- infra/k8s/redis-values.yaml
- infra/k8s/sidecar.yaml
- infra/k8s/tools/README.md
- infra/k8s/tools/confirm_dns_route.sh
- infra/k8s/tools/confirm_weave.sh
- manifests/dht.toml
- pkg/runner/cluster_k8s.go
TODO:
```
kubelet:
anonymousAuth: false
maxPods: 200
allowedUnsafeSysctls:
- net.core.somaxconn
```
> merge k8s setup steps together

- _meeting-notes/2020-01-21.md
Better late than never! I forgot to push these at the end of the last weekly.
> meeting notes testground weekly 2020-01-21

- sdk/runtime/files.go
This should make it obvious to users how test artifacts should be created.
(small PR to get this started)
> feat(runtime): create a simple "CreateArtifact" helper.

- manifests/example.toml
- plans/example/failure.go
- plans/example/go.mod
- plans/example/main.go
- plans/example/output.go
- plans/example/panic.go
- plans/example/params.go
- plans/example/sync.go
I wrote this primarily as a way for studying the SDK, and might be useful to future plan-writers or tests like the placebo test is already used.
Each file represents some small feature of the plan SDK.
> sdk examples

- docs/USAGE.md
This just updates the examples in USAGE.md to reflect the changes in #406.
> docs: remove references to runtime.OK, runtime.Abort from USAGE.md

- pkg/build/golang/docker.go
1. The go proxy doesn't need the source or binary directories.
2. There are some people, like me, who like to put different parts of their go path in different places and do funny things with symlinks.
> feat: only mount the pkg directory in the go proxy

- sdk/runtime/runenv.go
- sdk/runtime/runenv_test.go
Fixes: https://github.com/ipfs/testground/issues/447
> fix parsing of TEST_INSTANCE_PARAMS

- pkg/dockermanager/dockermanager.go
1. Log an error every 5 seconds when waiting.
2. Panic if we wait too long.
We don't want to just move on because we have a goroutine hanging.
> feat(sidecar): stop waiting for workers to finish

- docs/HOW_WE_WORK.md
Per #481, @raulk suggested I submit a PR for local time conversion.
> Add UTC→local time link in HOW_WE_WORK

- docs/USAGE.md
Fixes: https://github.com/ipfs/testground/issues/475
> update USAGE docs

- Makefile
- pkg/runner/cluster_k8s.go
- pkg/runner/cluster_swarm.go
- pkg/runner/local_docker.go
- pkg/runner/local_exec.go
- sdk/runtime/logger.go
- sdk/runtime/output.go
- sdk/runtime/runenv.go
- sdk/sync/redis_test.go
Apparently, find doesn't return a non-zero status when a command exits with a non-zero status.
> fix(make): fail on non-zero status

- docs/COMPOSITIONS.md
Related to https://github.com/ipfs/testground/issues/496
> note about build artifacts

- pkg/engine/engine.go
- pkg/runner/client_pool.go
- pkg/runner/cluster_k8s.go
Fixes https://github.com/ipfs/testground/issues/474
> handle canceled context in cluster_k8s.go

- pkg/sidecar/k8s_instance.go
Maybe fixes https://github.com/ipfs/testground/issues/514 but I haven't had a chance to test yet.
> fix: remove a runenv hack in the sidecar

- sdk/runtime/runenv.go
> runenv: flush logger on close.

- pkg/dockermanager/dockermanager.go
Currently the sidecar is throwing errors for normal operational conditions - for example a user starting a test plan and then hitting CTRL+C to stop it.
This will probably get more problematic when we move into running Testground as a service, as generally errors are something that should be looked at by developer and fixed.
This is an initial effort to downgrade some `normal operational conditions` from errors to warnings, or even traces.
> sidecar errors: check for context canceled

- pkg/runner/cluster_k8s.go
* Use continuations instead of startAfter
* Use contexts.
* Actually download sequentially.
> Fix some minor issues with the S3 collection logic

- .travis.yml
> chore: remove codecov

- pkg/runner/cluster_k8s.go
This will allow us to run `kubectl proxy` and review `pprof` output for individual pods when debugging a testplan.
---
We tested this with @aschmahmann and it works fine.
One only has to call `kubectl proxy` and then we have access to pprof at:
```
http://localhost:8001/api/v1/namespaces/default/pods/http:tg-dht-205d92ad7fb8-cypress-99:6060/proxy/debug/pprof/
```
provided that the testplan actually has it enabled (which we can add an env var in the future).
> add pprof port to pods

- sdk/sync/write.go
> fix(sdk/sync): don't panic on error if we're canceling anyways

- sdk/sync/common.go
- sdk/sync/redis_test.go
Instead of hammering the DNS server, resolve redis once when we first connect.
Related to #547.
> feat: resolve redis once

- infra/k8s/kops-weave/weave.yml
Fixes: https://github.com/ipfs/testground/issues/561
> weave wait for flannel - initContainer

- infra/k8s/install.sh
- infra/k8s/prometheus-pushgateway.yaml
- infra/k8s/redis-values.yaml
Install the prometheus pushgateway for short-lived tests
The values included are mostly from the stable helm chart,
but edited to take advantage of the prometheus operator.
> Add pushgateway

- pkg/docker/container.go
- pkg/runner/cluster_k8s.go
- pkg/runner/local_exec.go
* Store the outputsDir in the state.
* Locks.
> manage state of local:exec runner.

- .github/labels.yml
- .github/workflows/label-syncer.yml
Inspired by https://github.com/libp2p/libp2p/blob/master/ISSUE-LABELLING.md.
We can use as much of this as we want. For now, I'm interested in the area, hints, statuses, and priority labels.
> adopt an issue labelling scheme.

- plans/dht/test/tracers.go
Fix logging the same info twice.
> plans/dht/test: Remove duplicate log.

- dashboards/redis.json
This is the dashboard @nonsense made in https://github.com/ipfs/testground/pull/632
> Redis grafana dashboard

- infra/k8s/cluster.yaml
Fixes https://github.com/ipfs/testground/issues/594
> kubernetes 17 again

- infra/k8s/README.md
- infra/k8s/cluster.yaml
Fix: https://github.com/ipfs/testground/issues/593
> Remove broken dashboard

- infra/k8s/install.sh
- infra/k8s/kops-weave/weave-service-monitor.yml
Fixes: https://github.com/ipfs/testground/issues/634
instructions for adding this are here:
https://github.com/coreos/kube-prometheus/blob/master/docs/weave-net-support.md
I have not included the dashboard in this review, but I'll do that separately.
> weave monitoring

- infra/k8s/cluster.yaml
This reverts commit 130be85ea1012b5a79d64cca3493678f3d5f1735.
Issues:
https://github.com/ipfs/testground/issues/656
> Revert "kubernetes 17 again"

- infra/k8s/install.sh
- infra/k8s/kops-weave/weave-metrics-service.yml
- infra/k8s/kops-weave/weave-service-monitor.yml
I added the prometheus configuration earlier, and this provides the service endpoint
the weave endpoints look like this in prometheus
> weave scrape endpoint.

- infra/k8s/install.sh
- infra/k8s/kops-weave/weave-metrics-service.yml
This is a better way to do this.
> Use namespace in yml file rather than cli

- infra/k8s/README.md
I tripped over these, and enhanced the README to avoid tripping over them again.
> infra/k8s: clarify various points in the README.

- manifests/example.toml
- plans/example/go.mod
- plans/example/main.go
- plans/example/prometheus_3.go
Merged Anton's prometheus3, which was based on another branch than master, and there more merge conflicts than I want to deal with, so here it is again.
Same as: 
https://github.com/ipfs/testground/pull/675
> More prometheus examples from Anton

- .travis.yml
> build with go 1.14 in CI

- .travis.yml
- Makefile
Hopefully these changes will fix our linting woes on CI.
> fix makefile: explicitly set bash as shell; tune lint.

- pkg/runner/local_docker.go
- pkg/runner/local_exec.go
- pkg/runner/pretty.go
Fixes https://github.com/ipfs/testground/issues/696
> local:docker runner: rate limit starting and deleting containers.

- sdk/runtime/metrics.go
- sdk/runtime/runenv.go
- sdk/runtime/runner.go
Fixes https://github.com/ipfs/testground/issues/685
Fixes https://github.com/ipfs/testground/issues/598
Fixes https://github.com/ipfs/testground/issues/637
> wait for prometheus-pushgateway to be available

- infra/k8s/README.md
- pkg/runner/cluster_k8s.go
@aschmahmann Does this work on your system?
> Remove unnecessary shell

- compositions/uniq-artifacts.toml
- pkg/api/composition.go
- pkg/engine/engine.go
- plans/example/sync.go
Fixes #741.
cc @yusefnapora @aschmahmann
> engine: deduplicate group builds; perform only unique builds.

- plans/benchmarks/benchmarks.go
> fix lint errors

- .travis.yml
- pkg/docker/container.go
- pkg/docker/manager.go
- pkg/docker/volume.go
- pkg/runner/local_docker.go
Fixes https://github.com/ipfs/testground/issues/770
compare with https://github.com/ipfs/testground/pull/771 when reviewing
I have added regex filters to the EnsureContainer and EnsureVolume.
> docker filters: apply regex filtering

- env-example.toml
- pkg/conv/conversions.go
- pkg/runner/local_docker.go
Docker component of https://github.com/ipfs/testground/issues/781
apply higher ulimits to plan containers
> ulimits local:docker

- infra/k8s/install.sh
Sometimes download `kops` dependencies on the `master` takes a lot of time...
> wait longer for cluster validate

- pkg/api/composition.go
- pkg/api/runner.go
- pkg/engine/engine.go
- pkg/runner/cluster_k8s.go
- pkg/runner/common.go
- pkg/runner/local_docker.go
- pkg/runner/local_exec.go
Addresses https://github.com/ipfs/testground/issues/789
TODO:
> pod resources per composition group

- pkg/runner/cluster_k8s.go
This will be helpful when debugging issues with networking on Kubernetes.
cc @vyzo
> add pod ip to testplan env vars

- go.mod
- go.sum
> go mod tidy.

- pkg/sidecar/k8s_reactor.go
With this change, we have the following routing table
```
ip route
default via 24.0.0.0 dev eth1
24.0.0.0 dev eth1 scope link
30.180.0.0/16 dev eth1 scope link  src 30.180.8.7
blackhole 100.64.0.0/10
100.64.0.10 via 100.96.11.1 dev eth0
100.96.7.5 via 100.96.11.1 dev eth0
blackhole 100.96.11.0/24
```
> Blackhole the control network

- .circleci/config.yml
Use windows
download go 1.14
run go build.
> Circleci windows

- .github/labels.yml
Labels to add to YAML
Kind/investigation
Kind/chore
Status/ Approved-Waiting
Status/Changes Requested
Status/Waiting for Review
---
Closes #898.
> Update Yaml labels

- .circleci/config.yml
Set the size parameter on the windows orb
> medium sized windows

- .circleci/config.yml
merged by accident. Unmerging.
Reverts testground/testground#903
> Revert "medium sized windows"

- pkg/runner/cluster_k8s.go
1. Fixing a bug where we don't set the pod CPU and memory based on definition, but we are still using the defaults.
2. Reducing the CPU / memory limits for the `mkdir-outputs` container. It exits right at the start of execution, but no point requesting the defaults (which are 100m and 256Mi).
> set pod memory and cpu based on group definition

- pkg/sidecar/k8s_reactor.go
This is fixing a bug on `master` where `influxdb` env var is not set and host is `""`.
> sidecar/k8s: add name of service

- pkg/runner/cluster_k8s.go
We need to solve https://github.com/testground/testground/issues/875 rather than query the logs of 10k containers to find if a barrier has been passed.
> do not call wait-for-network-init

- pkg/config/loader.go
- pkg/runner/local_common.go
- pkg/runner/local_docker.go
- pkg/runner/local_exec.go
- pkg/sidecar/docker_reactor.go
Relates to:
https://github.com/testground/testground/issues/755
https://github.com/testground/testground/issues/907
https://github.com/testground/testground/issues/910
https://github.com/testground/testground/issues/908
https://github.com/testground/testground/issues/909
> inject influxdb env variables; fix sidecar; fix image.

- .github/labels.yml
cc @Robmat05 the GitHub action will erase any manually added labels!
> add "good first issue" and "help wanted" magic labels

- main.go
Currently we have:
```
NAME:
testground - A new cli application
```
---
With this PR, the output becomes:
```
NAME:
testground - a platform for testing, benchmarking, and simulating distributed and p2p systems at scale
USAGE:
testground [global options] command [command options] [arguments...]
DESCRIPTION:
testground is a platform for testing, benchmarking,and simulating distributed and p2p systems at scale.
COMMANDS:
build        request the daemon to build a test plan
collect      collect the output assets of the supplied run into a .tgz archive
daemon       start a long-running testground daemon process
describe     describe a test plan
healthcheck  validate/fix the preconditions for the runner to be able to operate properly
plan         manage the plans known to the client
run …
```
> replace "a new cli application" title

- pkg/rpc/rpc_test.go
- pkg/rpc/rpctest/rpctest.go
Separated out the rpctest component from https://github.com/testground/testground/pull/1009 since there was question about the usefulness of the docker test and this part is unrelated.
Fix: https://github.com/testground/testground/issues/1004
> `rpc` package tests

- pkg/runner/local_docker.go
- pkg/runner/pretty.go
Partially fixes: https://github.com/testground/testground/issues/1025
> append sidecar logs to testground output

- pkg/runner/cluster_k8s.go
- pkg/runner/registry.go
This PR is adding in-memory LRU cache for pushed Docker images to remote repositories. I think it is worth having this, because it removes >10sec. per image from test plan runs that are trying to submit images that have already been pushed to a given remote.
> LRU cache for pushed docker images

- pkg/runner/cluster_k8s.go
Follow up to https://github.com/testground/testground/pull/1057
> better error when misconfiguring .env.toml

- plans/benchmarks/compositions/storm.toml
- plans/benchmarks/go.mod
- plans/benchmarks/grafana-dashboard/storm.json
- plans/benchmarks/main.go
- plans/benchmarks/manifest.toml
- plans/benchmarks/storm.go
Trying to establish a baseline on the number of TCP connections we can establish between containers, considering that we are running Weave on the data plane.
> storm testplan

- pkg/sidecar/docker_reactor.go
- pkg/sidecar/instance.go
- pkg/sidecar/k8s_network.go
- pkg/sidecar/mock.go
- pkg/sidecar/sidecar_handler.go
- pkg/sidecar/sidecar_linux.go
Linting failed on my machine; then I realised that the sidecar tests did not compile under non-Linux OSes.
> make sidecar tests run everywhere.

- pkg/runner/cluster_k8s.go
Fixes https://github.com/testground/testground/issues/1073
> cluster_k8s: fix healthcheck deadlock

- pkg/runner/cluster_k8s.go
- pkg/runner/local_docker.go
This PR is adding `ExposedPorts` to the global run config, so that test plans can define the ports they want exposed on their test plan instances. For example on Lotus we want to be able to query APIs running on 1234 and 2345.
> user-defined exposed ports

- pkg/client/client.go
- pkg/config/env.go
- pkg/daemon/daemon.go
Partially addresses https://github.com/testground/testground/issues/1112
We will need something like this, once we spin up ingress for the daemon in the CI cluster.
---
FOLLOW UP TODO:
> basic auth functionality

- pkg/engine/engine.go
When given multiple unique builds to perform, we don't unpack the sources in unique directories to isolate each build. Thus all parallel builds end up sharing the source directory. This is fine for docker-based builds (as we tar the context and send it to the daemon, i.e. the source directory is read-only), not for local builders like `exec:go`, which share the file system and perform builds in-place.
This patch clones the sources into dedicated per-build directories, if multiple unique builds are requested.
> copy sources for each unique build.

- pkg/config/loader.go
- pkg/daemon/build.go
> fix regression in default client URL

- pkg/client/client.go
- pkg/cmd/build.go
- pkg/cmd/logs.go
- pkg/cmd/run.go
- pkg/daemon/daemon.go
- pkg/daemon/logs.go
- pkg/daemon/tasks.go
- pkg/engine/supervisor.go
This PR is adding 2 html pages - one with a list of `tasks`, one with the logs outputs for a given task.
TODO:
> html page showing tasks and logs

- pkg/api/engine.go
- pkg/cmd/tasks.go
- pkg/engine/engine.go
This is built on top of #1140 so it should be merged first (or this can be merged into that branch).
The first ones were tests that were stored on a different version of Testground, hence they were not storing test case nor plan.
(All commits are self-contained and self-explanatory)
> Improve CLI Tasks List

- plans/network/traffic.go
This PR is updating the network test plan to use `InitializedTestCaseFn`, reduce the code and update parts of the output.
> simplify network test plan

- pkg/healthcheck/checkers.go
This fixes #1202 but comes with a trade-off! In case you are running `testground-redis` container and your own Redis instance, it won't be detected and tests may fail. I updated the message that we print to the healthchecker so users are equipped with more information in order to solve an eventual issue.
Please also see this thread of comments: https://github.com/testground/testground/pull/1108/files#r460000688
License: MIT
> fix: redis port collision check

- pkg/runner/cluster_k8s.go
Handle the return error of `initPool`, fixing #1239.
I did not manually test this PR. @nonsense @raulk can you build this branch and check if #1239 is fixed?
License: MIT
> fix: handle k8s .initPool error

- .circleci/config.yml
> chore: update CI machine to newer LTS Ubuntu

- Makefile
- plans/example-js/.testgroundignore
- plans/example-js/README.md
- plans/example-js/package-lock.json
- plans/example-js/package.json
> chore: add node.js examples

- .github/labels.yml
* drop duplicated labels
* move dif => exp
* introduce kind/epic
* remove labels that are not directly actionable
* introduce SDK labels
* remove redundant statuses
> chores: simplify labels

- plans/network/pingpong.go
This is a proposal for how we could simplify address exchange in the ping pong test.
> share 1 addr per peer in the ping pong test

- plans/network/pingpong.go
Instances should not guess each other's address, because the allocated IP range may not match the code.
This PR forces the test instances to exchange their data IPs, so that they will attempt to connect to the correct IP.
Fixes one part of #1416 .
> Exchange IPs in pingpong test

- ROADMAP.md
Follow-up issue: https://github.com/testground/testground/issues/1491
> ROADMAP.md: Create our Roadmap

- .github/labels.yml
- .github/workflows/labels-sync.yml
Contributes to #1511: clarify labels
> .github/workflows: add labels sync
